### ISSUE TITLE
Can not start docker-homebridge in libreelec

### ISSUE THREAD

**Issue by trlsmax** [oznu/docker-homebridge#107]
Hi, thank for the great work on the docker images.
I want to run the docker container in libreelec docker plugin, but it did not work, I use the no-avahi version because there is avahi daemon running in the system.

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:5353
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at _handle.lookup (dgram.js:266:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

Hot to fix that ?

**Comment by oznu** [comment]
Disabling `avahi-daemon` on the host seems to work:

```
systemctl stop avahi-daemon
systemctl disable avahi-daemon
```

Run command I used to test:

```
docker run -d  --net=host \
  --name=homebridge \
  -e HOMEBRIDGE_CONFIG_UI=1 \
  -e HOMEBRIDGE_CONFIG_UI_PORT=58080 \
  oznu/homebridge:raspberry-pi
```
