### ISSUE TITLE
Hellup error 

### ISSUE THREAD

**Issue by henkied** [oznu/docker-homebridge#133]
Suddenly I have this error message, does anyone know why this is coming?

Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)

**Comment by henkied** [comment]
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[2018-10-4 22:33:59] Homebridge is running on port 51826.
[2018-10-4 22:33:59] [Doorbell] attachAccessory { uuid: 'bd2d0453-e202-42c2-ba2e-2b1436c77232',
  name: 'Front Door',
  manufacturer: 'Bot Home Automation, Inc.',
  model: 'lpd_v2',
  serialNumber: '7725234',
  firmwareRevision: 'Up to Date' }

/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106
    service.emit('error', new Error('Service name is already in use on the network'))
                          ^
Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
[2018-10-4 22:34:02] Loaded config.json with 1 accessories and 5 platforms.
[2018-10-4 22:34:02] ---
[2018-10-4 22:34:02] Plugin /homebridge/node_modules/homebridge-automation-switches requires Node version of >=9.3.0 which does not satisfy the current Node version of v8.12.0. You may need to upgrade your installation of Node.
[2018-10-4 22:34:02] Loaded plugin: homebridge-automation-switches
[2018-10-4 22:34:02] Registering platform 'homebridge-switches.AutomationSwitches'
[2018-10-4 22:34:02] ---
[2018-10-4 22:34:02] Loaded plugin: homebridge-delay-switch
[2018-10-4 22:34:02] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[2018-10-4 22:34:02] ---
[2018-10-4 22:34:03] Loaded plugin: homebridge-dyson-link
homebridge API version: 2.2
[2018-10-4 22:34:03] Registering platform 'homebridge-dyson-link.DysonPlatform'
[2018-10-4 22:34:03] ---
[2018-10-4 22:34:03] Loaded plugin: homebridge-eveatmo
[2018-10-4 22:34:03] Registering platform 'homebridge-eveatmo.eveatmo'
[2018-10-4 22:34:03] ---
[2018-10-4 22:34:03] Loaded plugin: homebridge-nest
[2018-10-4 22:34:03] Registering platform 'homebridge-nest.Nest'
[2018-10-4 22:34:03] ---
[2018-10-4 22:34:03] Loaded plugin: homebridge-platform-ring-video-doorbell
[2018-10-4 22:34:03] Registering platform 'homebridge-platform-ring-video-doorbell.ring-video-doorbell'
[2018-10-4 22:34:03] ---
[2018-10-4 22:34:03] Loaded plugin: homebridge-config-ui-x
[2018-10-4 22:34:03] Registering platform 'homebridge-config-ui-x.config'
[2018-10-4 22:34:03] ---
[2018-10-4 22:34:03] Loading 5 platforms...
[2018-10-4 22:34:03] [Doorbell] Initializing ring-video-doorbell platform...
[2018-10-4 22:34:03] [DysonPlatform] Initializing DysonPlatform platform...
[2018-10-4 22:34:03] [AutomationSwitches] Initializing AutomationSwitches platform...
[2018-10-4 22:34:03] [AutomationSwitches] AutomationSwitchesPlatform Plugin Loaded - Version 3.2.1
[2018-10-4 22:34:03] [AutomationSwitches] Found automation switch in config: "Automation Switch #1"
[2018-10-4 22:34:03] [AutomationSwitches] Found automation switch in config: "Nachtslot"
[2018-10-4 22:34:03] [AutomationSwitches] Switch Nachtslot is stored in file SecuritySystem.91C1310AF95A.json
[2018-10-4 22:34:03] [AutomationSwitches] Initializing platform accessory 'Automation Switch #1'...
[2018-10-4 22:34:03] [AutomationSwitches] Initializing platform accessory 'Nachtslot'...
[2018-10-4 22:34:03] [Nest] Initializing Nest platform...
[2018-10-4 22:34:03] [Nest] Fetching Nest devices.
[2018-10-4 22:34:03] [eveatmo platform] Initializing eveatmo platform...
[2018-10-4 22:34:04] [eveatmo platform] Loading new data from API for: weatherstation
[2018-10-4 22:34:04] Loading 1 accessories...
[2018-10-4 22:34:04] [deur op slot] Initializing DelaySwitch accessory...
Load homebridge-switches.AutomationSwitches
[2018-10-4 22:34:04] [homebridge-switches.AutomationSwitches] AutomationSwitchesPlatform Plugin Loaded - Version 3.2.1
[2018-10-4 22:34:04] [DysonPlatform] Dyson Configure Accessory
[2018-10-4 22:34:04] [Doorbell] configureAccessory { UUID: 'bd2d0453-e202-42c2-ba2e-2b1436c77232',
  displayName: 'Front Door' }
[2018-10-4 22:34:04] [Doorbell] didFinishLaunching
[2018-10-4 22:34:04] [DysonPlatform] Finished launching. Start to create accessory from config
[2018-10-4 22:34:04] [eveatmo platform] Initializing platform accessory 'Woonkamer Binnen'...
[2018-10-4 22:34:04] [eveatmo platform] Initializing platform accessory 'Woonkamer Buiten'...
[2018-10-4 22:34:04] [eveatmo platform] Initializing platform accessory 'Woonkamer Regen'...
[2018-10-4 22:34:04] [DysonPlatform] Dyson IP:10.0.1.140 Serial Number:DYSON-VS9-EU-KFA3482A-438
[2018-10-4 22:34:05] [DysonPlatform] Device serial number format valids
[2018-10-4 22:34:05] [DysonPlatform] Device cached. Try to update this
[2018-10-4 22:34:05] [DysonPlatform] Init Sensor for Dyson
[2018-10-4 22:34:05] [DysonPlatform] Init Fan State for Dyson
[2018-10-4 22:34:05] [DysonPlatform] Auto switch found. Remove this now
[2018-10-4 22:34:05] [DysonPlatform] Night mode button is added
HAP Warning: Characteristic 000000BF-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000B7-0000-1000-8000-0026BB765291. Adding anyway.
[2018-10-4 22:34:05] [DysonPlatform] Connected to VS9-EU-KFA3482A. subscribe now
[2018-10-4 22:34:06] [Doorbell] refresh1 { username: 'xxxxx@xxx.xxx',
  diagnostic: 'Error: JSON parse error from ring, check logging..' }
[2018-10-4 22:34:07] [Nest] initing protect "Zolder Nest Protect": deviceId: 5izLlKeBvzQSLBuK4gVrBkcO3x-bX9H5 structureId: va-j4iv6Q5HOEByPctCQeAhdOz7ivgyYc_0xC00iGiA1TGkuKn3FYA
[2018-10-4 22:34:07] [Nest] initing protect "Family Room Nest Protect": deviceId: 5izLlKeBvzRm_YNoOIzo30cO3x-bX9H5 structureId: va-j4iv6Q5HOEByPctCQeAhdOz7ivgyYc_0xC00iGiA1TGkuKn3FYA
[2018-10-4 22:34:07] [Nest] initing protect "Kitchen Nest Protect": deviceId: 5izLlKeBvzSunQsNGYJ-60cO3x-bX9H5 structureId: va-j4iv6Q5HOEByPctCQeAhdOz7ivgyYc_0xC00iGiA1TGkuKn3FYA
[2018-10-4 22:34:07] [Nest] Initializing platform accessory 'Zolder Nest Protect'...
[2018-10-4 22:34:07] [Nest] Initializing platform accessory 'Family Room Nest Protect'...
[2018-10-4 22:34:07] [Nest] Initializing platform accessory 'Kitchen Nest Protect'...
Setup Payload:
X-HM://0023ISYWYFPE4
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

**Comment by henkied** [comment]
The whole log file:

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[2018-10-4 22:44:16] Homebridge is running on port 51826.

/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106
    service.emit('error', new Error('Service name is already in use on the network'))
                          ^
Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
[2018-10-4 22:44:19] Loaded config.json with 1 accessories and 4 platforms.
[2018-10-4 22:44:19] ---
[2018-10-4 22:44:19] Plugin /homebridge/node_modules/homebridge-automation-switches requires Node version of >=9.3.0 which does not satisfy the current Node version of v8.12.0. You may need to upgrade your installation of Node.
[2018-10-4 22:44:19] Loaded plugin: homebridge-automation-switches
[2018-10-4 22:44:19] Registering platform 'homebridge-switches.AutomationSwitches'
[2018-10-4 22:44:19] ---
[2018-10-4 22:44:19] Loaded plugin: homebridge-delay-switch
[2018-10-4 22:44:19] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[2018-10-4 22:44:19] ---
[2018-10-4 22:44:19] Loaded plugin: homebridge-dyson-link
homebridge API version: 2.2
[2018-10-4 22:44:19] Registering platform 'homebridge-dyson-link.DysonPlatform'
[2018-10-4 22:44:19] ---
[2018-10-4 22:44:20] Loaded plugin: homebridge-eveatmo
[2018-10-4 22:44:20] Registering platform 'homebridge-eveatmo.eveatmo'
[2018-10-4 22:44:20] ---
[2018-10-4 22:44:20] Loaded plugin: homebridge-nest
[2018-10-4 22:44:20] Registering platform 'homebridge-nest.Nest'
[2018-10-4 22:44:20] ---
[2018-10-4 22:44:20] Loaded plugin: homebridge-config-ui-x
[2018-10-4 22:44:20] Registering platform 'homebridge-config-ui-x.config'
[2018-10-4 22:44:20] ---
[2018-10-4 22:44:20] Loading 4 platforms...
[2018-10-4 22:44:20] [DysonPlatform] Initializing DysonPlatform platform...
[2018-10-4 22:44:20] [AutomationSwitches] Initializing AutomationSwitches platform...
[2018-10-4 22:44:20] [AutomationSwitches] AutomationSwitchesPlatform Plugin Loaded - Version 3.2.1
[2018-10-4 22:44:20] [AutomationSwitches] Found automation switch in config: "Automation Switch #1"
[2018-10-4 22:44:20] [AutomationSwitches] Found automation switch in config: "Nachtslot"
[2018-10-4 22:44:20] [AutomationSwitches] Switch Nachtslot is stored in file SecuritySystem.91C1310AF95A.json
[2018-10-4 22:44:20] [AutomationSwitches] Initializing platform accessory 'Automation Switch #1'...
[2018-10-4 22:44:20] [AutomationSwitches] Initializing platform accessory 'Nachtslot'...
[2018-10-4 22:44:20] [Nest] Initializing Nest platform...
[2018-10-4 22:44:20] [Nest] Fetching Nest devices.
[2018-10-4 22:44:20] [eveatmo platform] Initializing eveatmo platform...
[2018-10-4 22:44:20] [eveatmo platform] Loading new data from API for: weatherstation
[2018-10-4 22:44:20] Loading 1 accessories...
[2018-10-4 22:44:20] [deur op slot] Initializing DelaySwitch accessory...
Load homebridge-switches.AutomationSwitches
[2018-10-4 22:44:20] [homebridge-switches.AutomationSwitches] AutomationSwitchesPlatform Plugin Loaded - Version 3.2.1
[2018-10-4 22:44:20] [DysonPlatform] Dyson Configure Accessory
Failed to find plugin to handle accessory Front Door
[2018-10-4 22:44:21] [DysonPlatform] Finished launching. Start to create accessory from config
[2018-10-4 22:44:21] [eveatmo platform] Initializing platform accessory 'Woonkamer Binnen'...
[2018-10-4 22:44:21] [eveatmo platform] Initializing platform accessory 'Woonkamer Buiten'...
[2018-10-4 22:44:21] [eveatmo platform] Initializing platform accessory 'Woonkamer Regen'...
[2018-10-4 22:44:21] [DysonPlatform] Dyson IP:10.0.1.140 Serial Number:DYSON-VS9-EU-KFA3482A-438
[2018-10-4 22:44:21] [DysonPlatform] Device serial number format valids
[2018-10-4 22:44:21] [DysonPlatform] Device cached. Try to update this
[2018-10-4 22:44:21] [DysonPlatform] Init Sensor for Dyson
[2018-10-4 22:44:21] [DysonPlatform] Init Fan State for Dyson
[2018-10-4 22:44:21] [DysonPlatform] Auto switch found. Remove this now
[2018-10-4 22:44:21] [DysonPlatform] Night mode button is added
HAP Warning: Characteristic 000000BF-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000B7-0000-1000-8000-0026BB765291. Adding anyway.
[2018-10-4 22:44:22] [DysonPlatform] Connected to VS9-EU-KFA3482A. subscribe now
[2018-10-4 22:44:23] [Nest] initing protect "Zolder Nest Protect": deviceId: 5izLlKeBvzQSLBuK4gVrBkcO3x-bX9H5 structureId: va-j4iv6Q5HOEByPctCQeAhdOz7ivgyYc_0xC00iGiA1TGkuKn3FYA
[2018-10-4 22:44:23] [Nest] initing protect "Family Room Nest Protect": deviceId: 5izLlKeBvzRm_YNoOIzo30cO3x-bX9H5 structureId: va-j4iv6Q5HOEByPctCQeAhdOz7ivgyYc_0xC00iGiA1TGkuKn3FYA
[2018-10-4 22:44:23] [Nest] initing protect "Kitchen Nest Protect": deviceId: 5izLlKeBvzSunQsNGYJ-60cO3x-bX9H5 structureId: va-j4iv6Q5HOEByPctCQeAhdOz7ivgyYc_0xC00iGiA1TGkuKn3FYA
[2018-10-4 22:44:23] [Nest] Initializing platform accessory 'Zolder Nest Protect'...
[2018-10-4 22:44:23] [Nest] Initializing platform accessory 'Family Room Nest Protect'...
[2018-10-4 22:44:23] [Nest] Initializing platform accessory 'Kitchen Nest Protect'...
Setup Payload:
X-HM://0023ISYWYFPE4
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

**Comment by henkied** [comment]
@oznu can you help?
