### ISSUE TITLE
Error: Service name is already in use on the network

### ISSUE THREAD

**Issue by henkied** [oznu/docker-homebridge#134]
I have also placed this error message in slack, maybe someone here knows the solution:

Suddenly I have this error message, does anyone know why this is coming?

**Error: Service name is already in use on the network**
at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
at emitTwo (events.js:126:13)
at EventEmitter.emit (events.js:214:7)
at Socket. (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
at emitTwo (events.js:126:13)
at Socket.emit (events.js:214:7)
at UDP.onMessage (dgram.js:659:8)

oznu [9:33 AM]
@Henk Try renaming homebridge in the config.json. bridge -> name.

Henk [9:40 AM]
@oznu Thanks, I will try when I am home. Strange is that after a while homebridge is online again and the error message no longer occurs. When I mutate the config, the error message comes back .... etc

Henk [9:18 AM]
**@oznu Unfortunately it did not help ...., he continues to give the above error**

**Comment by henkied** [comment]
@oznu i have remove all ass and platforms..remove homebridge from package center. And have clean install still the error is there ??

[2018-10-6 11:46:31] Homebridge is running on port 51826.

/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106
    service.emit('error', new Error('Service name is already in use on the network'))
                          ^
Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
[2018-10-6 11:46:34] Loaded config.json with 0 accessories and 0 platforms.
[2018-10-6 11:46:34] ---
[2018-10-6 11:46:34] Loaded plugin: homebridge-config-ui-x
[2018-10-6 11:46:34] Registering platform 'homebridge-config-ui-x.config'
[2018-10-6 11:46:34] ---
[2018-10-6 11:46:34] Loading 0 platforms...
[2018-10-6 11:46:34] Loading 0 accessories...
Setup Payload:
X-HM://0024V21Q8JFK5
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

**Comment by henkied** [comment]
Strange i see that the discription is change see "bold"  ??



[2018-10-6 13:09:39] Homebridge is running on port 51826.

/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106
    service.emit('error', new Error('Service name is already in use on the network'))
                          ^
Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    **at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)**
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)
