### ISSUE TITLE
homebridge-dacp not working: dns service error: unknown

### ISSUE THREAD

**Issue by fugazzy** [oznu/docker-homebridge#196]
I am trying to get homebridge-dacp to run, but I end up always with the same error.
I used: latest / no-avahi, debian-no-avahi  (Avahi causes problems)
DS918+  (tried: host network and macvlan)
`
[37m[5/5/2019, 9:47:17 AM][39m [36m[DACP][39m Initializing DACP platform...
[37m[5/5/2019, 9:47:17 AM][39m [36m[DACP][39m DACP Platform Plugin Loaded - Version 0.9.2
[37m[5/5/2019, 9:47:17 AM][39m [36m[DACP][39m Found accessory in config: "AppleTV"
[37m[5/5/2019, 9:47:17 AM][39m [36m[DACP][39m 
[37m[5/5/2019, 9:47:17 AM][39m [36m[DACP][39m Skipping creation of the accessory "AppleTV" because it doesn't have a pairing code or
[37m[5/5/2019, 9:47:17 AM][39m [36m[DACP][39m service name yet. You need to pair the device/iTunes, reconfigure and restart homebridge.
[37m[5/5/2019, 9:47:17 AM][39m [36m[DACP][39m 
[37m[5/5/2019, 9:47:17 AM][39m [36m[DACP][39m Beginning remote control announcements for the accessory "AppleTV".
[37m[5/5/2019, 9:47:17 AM][39m [36m[DACP][39m 
[37m[5/5/2019, 9:47:17 AM][39m [36m[DACP][39m 	Use passcode 9740 to pair with this remote control.
[37m[5/5/2019, 9:47:17 AM][39m [36m[DACP][39m 
[37m[5/5/2019, 9:47:17 AM][39m [1m[31mError: dns service error: unknown
    at new Advertisement (/homebridge/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/homebridge/node_modules/mdns/lib/advertisement.js:64:10)
    at new DacpRemote (/homebridge/node_modules/homebridge-dacp/src/dacp/DacpRemote.js:29:21)
    at DacpPlatform._createRemote (/homebridge/node_modules/homebridge-dacp/src/index.js:215:24)
    at _accessories.devices.map.device (/homebridge/node_modules/homebridge-dacp/src/index.js:194:14)
    at Array.map (<anonymous>)
    at DacpPlatform.accessories (/homebridge/node_modules/homebridge-dacp/src/index.js:174:33)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:341:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)[39m[22m
[37m[5/5/2019, 9:47:17 AM][39m Got SIGTERM, shutting down Homebridge...
`

**Comment by oznu** [comment]
You can't use the `no-avahi` images with `homebridge-dacp` as it still depends on the `mdns` package (which Homebridge moved away from).

I'll leave this one for the plugin author: https://github.com/grover/homebridge-dacp/issues/63
