### ISSUE TITLE
net=host and Avahi

### ISSUE THREAD

**Issue by darvin** [oznu/docker-homebridge#197]
if I set net=host, what is recommended configuration of the host? I run ubuntu host, so it runs dbus but not Avahi.

im getting those errors while trying to get Homebridge-apple-tv work on this docker image:

```
/usr/local/lib/node_modules/node-appletv/node_modules/mdns/lib/browser.js:86
  dns_sd.DNSServiceBrowse(self.serviceRef, flags, ifaceIdx, '' + requested_type,
         ^

Error: dns service error: unknown
    at new Browser (/usr/local/lib/node_modules/node-appletv/node_modules/mdns/lib/browser.js:86:10)
    at Object.create [as createBrowser] (/usr/local/lib/node_modules/node-appletv/node_modules/mdns/lib/browser.js:114:10)
```

**Comment by darvin** [comment]
when I start image with Avahi I see in logs:

```
homebridge       | [cont-init.d] 40-dbus-avahi: exited 0.
```

**Comment by darvin** [comment]
never mind, working configuration on ubuntu is following:
dbus on ubuntu host: enabled
Avahi on ubuntu host: disabled

debian-avahi image
