### ISSUE TITLE
Error removing falkbulb

### ISSUE THREAD

**Issue by CyrusSUEN** [oznu/docker-homebridge#2]
Thank you developer for your effort! 
I've successfully turned my Raspberry Pi 3 into a Homebridge running on Docker to control my Yeelight lightbulb. 👍 

However I'm new to Docker and Homebridge and I'm not sure how to completely remove the fakebulb. 
Is there a way to completely remove it before getting the container running?
I've got an error when running the cmd for the docker container to remove the fakebulb as well.
Here is the log:

```bash
pi@raspberrypi:~/docker-images$ docker exec 2ddf2ba19865 yarn remove homebridge-fakebulb
yarn remove v0.24.4
[1/2] Removing module homebridge-fakebulb...
[2/2] Regenerating lockfile and installing missing dependencies...
warning No license field
warning homebridge-yeelight@0.0.16: The engine "homebridge" appears to be invalid.
success Uninstalled packages.
Done in 3.45s.
pi@raspberrypi:~/docker-images$ cd docker-homebridge/
pi@raspberrypi:~/docker-images/docker-homebridge$ ls
2  default.config.json	docker-compose.yml  Dockerfile	Dockerfile.raspberry-pi  init.d  README.md
pi@raspberrypi:~/docker-images/docker-homebridge$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS               NAMES
2ddf2ba19865        oznu/homebridge:raspberry-pi   "/init.d/entrypoin..."   19 minutes ago      Up 19 minutes                           dockerhomebridge_homebridge_1
pi@raspberrypi:~/docker-images/docker-homebridge$ docker-compose down
Stopping dockerhomebridge_homebridge_1 ... done
Removing dockerhomebridge_homebridge_1 ... done
pi@raspberrypi:~/docker-images/docker-homebridge$ docker-compose up
Creating dockerhomebridge_homebridge_1
Attaching to dockerhomebridge_homebridge_1
homebridge_1  | sh: Kong": unknown operand
homebridge_1  | Removing old plugins...
homebridge_1  | npm WARN package.json @ No description
homebridge_1  | npm WARN package.json @ No repository field.
homebridge_1  | npm WARN package.json @ No README data
homebridge_1  | npm WARN package.json @ No license field.
homebridge_1  | Installing plugins...
homebridge_1  | yarn install v0.24.4
homebridge_1  | warning No license field
homebridge_1  | [1/4] Resolving packages...
homebridge_1  | success Already up-to-date.
homebridge_1  | Done in 1.47s.
homebridge_1  | *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
homebridge_1  | *** WARNING *** Please fix your application to use the native API of Avahi!
homebridge_1  | *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
homebridge_1  | *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
homebridge_1  | *** WARNING *** Please fix your application to use the native API of Avahi!
homebridge_1  | *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
homebridge_1  | failed to load BLE module!
homebridge_1  | [6/22/2017, 9:02:29 AM] Loaded plugin: homebridge-yeelight
homebridge_1  | [6/22/2017, 9:02:29 AM] Registering platform 'homebridge-yeelight.yeelight'
homebridge_1  | [6/22/2017, 9:02:29 AM] ---
homebridge_1  | [6/22/2017, 9:02:29 AM] Loaded config.json with 1 accessories and 0 platforms.
homebridge_1  | [6/22/2017, 9:02:29 AM] ---
homebridge_1  | [6/22/2017, 9:02:29 AM] Loading 0 platforms...
homebridge_1  | [6/22/2017, 9:02:29 AM] Loading 1 accessories...
homebridge_1  | /usr/local/lib/node_modules/homebridge/lib/api.js:64
homebridge_1  |       throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
homebridge_1  |       ^
homebridge_1  | 
homebridge_1  | Error: The requested accessory 'FakeBulb' was not registered by any plugin.
homebridge_1  |     at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
homebridge_1  |     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
homebridge_1  |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
homebridge_1  |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
homebridge_1  |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge_1  |     at Module._compile (module.js:570:32)
homebridge_1  |     at Object.Module._extensions..js (module.js:579:10)
homebridge_1  |     at Module.load (module.js:487:32)
homebridge_1  |     at tryModuleLoad (module.js:446:12)
homebridge_1  |     at Function.Module._load (module.js:438:3)
dockerhomebridge_homebridge_1 exited with code 1
```

**Comment by oznu** [comment]
Have you removed the entry from the [config.json](https://github.com/oznu/docker-homebridge/blob/master/default.config.json) as well?

I'm thinking I might just remove the fake bulb example.

**Comment by CyrusSUEN** [comment]
Thanks the reply!
I've solved this by removing the fake bulb from config.json and package.json file. 
I've also mounted a volume in the docker-compose file.

docker-compose.yml:
```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    environment:
      - TZ=Australia/Sydney
    volumes:
      - ./.homebridge:/homebridge
```

Changed the content of files [./default.package.json](https://github.com/oznu/docker-homebridge/blob/master/default.config.json) and ./.homebridge/package.json in the mounted volume to
```json
{
  "dependencies": {
    "homebridge-yeelight": "0.0.16"
  }
}
