### ISSUE TITLE
Node Version Issue?

### ISSUE THREAD

**Issue by mikestecker** [oznu/docker-homebridge#241]
**Describe Your Problem:**
Homebridge plugin causing a crash loop with Homebridge due to a Node version issue? Is there a way to specify the node version?

**Logs:**

```
[10/22/2019, 10:46:20 AM] ====================
[10/22/2019, 10:46:20 AM] ERROR LOADING PLUGIN homebridge-unifi-protect-camera-motion:
[10/22/2019, 10:46:20 AM] Error: The module '/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/lib/canvas.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-unifi-protect-camera-motion/node_modules/canvas/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
[10/22/2019, 10:46:20 AM] ====================
```

**Docker Start Command:**
```
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:debian
    restart: always
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PACKAGES=ffmpeg,build-essential,g++,libpng-dev,libjpeg-dev,libpango1.0-dev,libcairo2-dev,libgif-dev,libfreetype6-dev
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_DEBUG=0
      - HOMEBRIDGE_CONFIG_UI_PORT=8089
    volumes:
      - ${USERDIR}/docker/homebridge:/homebridge
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "REDACTED",
        "port": 51826,
        "pin": "REDACTED",
        "mdns": {
            "interface": "REDACTED"
        }
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "Nest",
            "token": "REDACTED",
            "clientId": "REDACTED",
            "clientSecret": "REDACTED",
            "code": "REDACTED"
        },
        {
            "platform": "Nest-cam",
            "access_token": "REDACTED",
            "ffmpegCodec": "libx264"
        },
        {
            "platform": "Unifi-Protect-Camera-Motion",
            "name": "Unifi protect cameras & motion sensors",
            "unifi": {
                "controller": "REDACTED",
                "controller_rtsp": "REDACTED",
                "username": "REDACTED",
                "password": "REDACTED",
                "motion_interval": 5000,
                "motion_repeat_interval": 30000,
                "motion_score": 50,
                "enhanced_motion": true,
                "enhanced_motion_score": 50,
                "enhanced_classes": [
                    "person",
                    "car",
                    "truck"
                ],
                "debug": false
            },
            "videoConfig": {
                "vcodec": "h264",
                "audio": false,
                "maxStreams": 4,
                "maxWidth": 1024,
                "maxHeight": 576,
                "maxFPS": 30,
                "mapvideo": "0:1",
                "mapaudio": "0:0"
            }
        },
        {
            "platform": "WeatherPlus",
            "name": "WeatherPlus",
            "service": "openweathermap",
            "key": "REDACTED",
            "location": REDACTED,
            "locationCity": "REDACTED",
            "locationGeo": [
                REDACTED,
                REDACTED
            ],
            "language": "en"
        }
    ]
}
```

**Environment:**

* **Host Operating System**: Ubuntu 18.04.3 LTS
* **Docker Version**: Docker version 19.03.0-rc3, build 27fcb77
* **Image Tag / Type**: `debian`

**Comment by oznu** [comment]
The logs provide the solution, run this in the container:

```
npm rebuild
```

Or delete the `/homebridge/node_modules` and restart the container (not just Homebridge).
