### ISSUE TITLE
ENOSPC No space left issue on Docker on NAS

### ISSUE THREAD

**Issue by thechrisreese** [oznu/docker-homebridge#25]
Thoughts? 

3/4] Linking dependencies...                                                                                                                  
error Could not write file "/homebridge/yarn-error.log": "ENOSPC: no space left on device, write"                                              
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.                                                       
error An unexpected error occurred: "ENOSPC: no space left on device, write".

**Comment by oznu** [comment]
What platform and plugins are you using?

**Comment by thechrisreese** [comment]
Spent some time on this yesterday. Apparently the QNAP NAS has an issue with its tmpfs after firmware updates. Had to totally uninstall container and docker and reboot several times before it would clear out. Gave me a chance to install Homebridge in a slightly better place and now it’s running fine.

**Comment by jeylites** [comment]
Hello, 

I'm having the same issue on Raspberry pi "ENOSPC: no space left on device, write" 

How to fix this without uninstalling the docker container?

**Comment by jeylites** [comment]
Here are the messages form the logs

```
[12/3/2020, 6:02:08 AM] Error: ENOSPC: no space left on device, write
    at Object.writeSync (fs.js:581:3)
    at Object.writeFileSync (fs.js:1275:26)
    at LocalStorage.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:476:16)
    at LocalStorage.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:277:14)
    at Server.saveCachedPlatformAccessoriesOnDisk (/usr/local/lib/node_modules/homebridge/src/server.ts:318:24)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:613:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:64:12)
    at process.emit (events.js:210:5)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:495:21)
```
