### ISSUE TITLE
update node.js 

### ISSUE THREAD

**Issue by henkied** [oznu/docker-homebridge#261]
I am not entirely handy with the following:
I have installed 3 hombridge, because some plugins conflict with each other.

homebridge ring
homebridge dyson
homebridge-other

If runs on a synology nas 718, and works great!
BUT I have to update the node.js and that doesn't work!

I have installed homebridge-ring with packet. This update is fine after restart.

I have to update the other 2 dyson and other in a different way and that doesn't work.

I am not handy with sudo and terminal.

If I follow Oznu's instruction: https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology#updating-homebridge

Then he stays on the old node.

Can someone explain to me how I can update this?

Thanks

**Comment by oznu** [comment]
@henkied - the other option is to delete your existing contains in DSM and follow the steps to set them up again after pulling the latest image down. If you pass in same `/homebridge` volume mount you shouldn't lose any config / HomeKit pairings.

---

Alternatively, you can upgrade Node.js inside the existing containers, but you should only do this as a last resort. You can run all these commands in the Homebridge Config UI X web terminal.

First, check that you are using the "Alpine Linux" container:

```bash
cat /etc/os-release | grep "NAME"
# Make sure the output says "Alpine Linux" - do not proceed if it says Debian.
```

Update Node.js (amd64 / x86_64 systems):

```bash
curl -Lf "https://github.com/oznu/alpine-node/releases/download/12.14.1/node-v12.14.1-linux-x86_64-alpine.tar.gz" | tar xzf - -C /usr --strip-components=1 --no-same-owner
```

Check new Node.js version:

```bash
node -v
# 12.14.1
```

Rebuild global modules:

```
cd $(npm -g prefix)/lib/node_modules && npm rebuild
```

Rebuild plugins:

```
cd /homebridge && npm rebuild
```

Restart Homebridge.

**Comment by henkied** [comment]
Thanks for your comment!

I understand. one more question, which container should I take? how can i check that?

**Comment by oznu** [comment]
>  which container should I take? 

Can you clarify what you mean here?

**Comment by henkied** [comment]
Sure! .. when downloading the image in the docker on my synology nas I can choose from different versions what is the right one to choose?
<img width="202" alt="Schermafdruk 2020-01-13 10 47 32" src="https://user-images.githubusercontent.com/20031014/72246683-92890600-35f3-11ea-944a-9becf1c5f740.png">

**Comment by oznu** [comment]
`latest` should be what you want usually.

**Comment by iRonin** [comment]
I updated node as per the instructions above but now I get the following error and cannot update plugins, Homebridge works after restart @oznu 

```
/homebridge # cat /root/.npm/_logs/2020-03-31T09_42_23_354Z-debug.log                                                                                         
0 info it worked if it ends with ok                                                                                                                           
1 verbose cli [                                                                                                                                               
1 verbose cli   '/usr/local/bin/node',                                                                                                                        
1 verbose cli   '/usr/local/bin/npm',                                                                                                                         
1 verbose cli   'install',                                                                                                                                    
1 verbose cli   '--save',                                                                                                                                     
1 verbose cli   'homebridge-ifttt@latest'                                                                                                                     
1 verbose cli ]                                                                                                                                               
2 info using npm@6.13.4                                                                                                                                       
3 info using node@v12.14.1                                                                                                                                    
4 verbose npm-session c33f78f917e9f81c                                                                                                                        
5 silly install loadCurrentTree                                                                                                                               
6 silly install readLocalPackageData                                                                                                                          
7 silly fetchPackageMetaData error for homebridge-ifttt@latest Cannot read property 'resolve' of undefined                                                    
8 timing stage:rollbackFailedOptional Completed in 2ms                                                                                                        
9 timing stage:runTopLevelLifecycles Completed in 1740ms                                                                                                      
10 verbose stack TypeError: Cannot read property 'resolve' of undefined                                                                                       
10 verbose stack     at regFetch (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js:76:23)                                             
10 verbose stack     at fetchPackument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:42:10)                         
10 verbose stack     at packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:20:10)                              
10 verbose stack     at getManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:22:10)                             
10 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:13:10)                                
10 verbose stack     at Object.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/index.js:17:12)                            
10 verbose stack     at Object.Fetcher#manifest [as manifest] (/usr/local/lib/node_modules/npm/node_modules/genfun/lib/genfun.js:15:38)                       
10 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetch.js:23:18)                                                     
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/manifest.js:24:12                                                                 
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:29:24                                                       
10 verbose stack     at Promise._execute (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/debuggability.js:313:9)                            
10 verbose stack     at Promise._resolveFromExecutor (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:488:18)                     
10 verbose stack     at new Promise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:79:10)                                       
10 verbose stack     at _inflight (/usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:28:25)                                           
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:22:14                                                       
10 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)                                           
11 verbose cwd /homebridge                                                                                                                                    
12 verbose Linux 4.4.59+                                                                                                                                      
13 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "homebridge-ifttt@latest"                                                       
14 verbose node v12.14.1                                                                                                                                      
15 verbose npm  v6.13.4                                                                                                                                       
16 error Cannot read property 'resolve' of undefined                                                                                                          
17 verbose exit [ 1, true ]      
```

**Comment by iRonin** [comment]
Above was solved by updating npm.

@oznu what's the latest node that can be installed?

**Comment by oznu** [comment]
[LTS](https://nodejs.org/en/) is the latest available. The recommended way of updating Node.js is to pull the latest Docker image, which will always (within a day) is up-to-date.
