### ISSUE TITLE
Host name conflict

### ISSUE THREAD

**Issue by skbeez** [oznu/docker-homebridge#269]
Problem Description:
I keep getting a host name conflict with multiple instances of home bridge. I moved one of the two to another raspberry pi because I thought that may have been the issue, but I still have the same issue.

**Logs:**
```
homebridge-pihole_1  | Host name conflict, retrying with raspberrypi-61
homebridge-pihole_1  | Registering new address record for 172.17.0.1 on docker0.IPv4.
homebridge-pihole_1  | Registering new address record for fe80::afd5:4dc4:16bf:ee5 on eth0.*.
homebridge-pihole_1  | Registering new address record for 192.168.1.15 on eth0.IPv4.
homebridge-pihole_1  | Withdrawing address record for fe80::afd5:4dc4:16bf:ee5 on eth0.
homebridge-pihole_1  | Withdrawing address record for 192.168.1.15 on eth0.
homebridge-pihole_1  | Host name conflict, retrying with raspberrypi-62
homebridge-pihole_1  | Registering new address record for 172.17.0.1 on docker0.IPv4.
homebridge-pihole_1  | Registering new address record for fe80::afd5:4dc4:16bf:ee5 on eth0.*.
homebridge-pihole_1  | Registering new address record for 192.168.1.15 on eth0.IPv4.
homebridge-pihole_1  | Withdrawing address record for fe80::afd5:4dc4:16bf:ee5 on eth0.
homebridge-pihole_1  | Withdrawing address record for 192.168.1.15 on eth0.
homebridge-pihole_1  | Host name conflict, retrying with raspberrypi-63
homebridge-pihole_1  | Registering new address record for 172.17.0.1 on docker0.IPv4.
homebridge-pihole_1  | Registering new address record for fe80::afd5:4dc4:16bf:ee5 on eth0.*.
homebridge-pihole_1  | Registering new address record for 192.168.1.15 on eth0.IPv4.
homebridge-pihole_1  | Withdrawing address record for fe80::afd5:4dc4:16bf:ee5 on eth0.
homebridge-pihole_1  | Withdrawing address record for 192.168.1.15 on eth0.
homebridge-pihole_1  | Host name conflict, retrying with raspberrypi-64
homebridge-pihole_1  | Registering new address record for 172.17.0.1 on docker0.IPv4.
homebridge-pihole_1  | Registering new address record for fe80::afd5:4dc4:16bf:ee5 on eth0.*.
homebridge-pihole_1  | Registering new address record for 192.168.1.15 on eth0.IPv4.
homebridge-pihole_1  | Withdrawing address record for fe80::afd5:4dc4:16bf:ee5 on eth0.
homebridge-pihole_1  | Withdrawing address record for 192.168.1.15 on eth0.
homebridge-pihole_1  | Host name conflict, retrying with raspberrypi-65
homebridge-pihole_1  | Registering new address record for 172.17.0.1 on docker0.IPv4.
homebridge-pihole_1  | Registering new address record for fe80::afd5:4dc4:16bf:ee5 on eth0.*.
homebridge-pihole_1  | Registering new address record for 192.168.1.15 on eth0.IPv4.
homebridge-pihole_1  | Withdrawing address record for fe80::afd5:4dc4:16bf:ee5 on eth0.
homebridge-pihole_1  | Withdrawing address record for 192.168.1.15 on eth0.
homebridge-pihole_1  | Host name conflict, retrying with raspberrypi-66
homebridge-pihole_1  | Registering new address record for 172.17.0.1 on docker0.IPv4.
homebridge-pihole_1  | Registering new address record for fe80::afd5:4dc4:16bf:ee5 on eth0.*.
homebridge-pihole_1  | Registering new address record for 192.168.1.15 on eth0.IPv4.
homebridge-pihole_1  | Withdrawing address record for fe80::afd5:4dc4:16bf:ee5 on eth0.
homebridge-pihole_1  | Withdrawing address record for 192.168.1.15 on eth0.
homebridge-pihole_1  | Host name conflict, retrying with raspberrypi-67
homebridge-pihole_1  | Registering new address record for 172.17.0.1 on docker0.IPv4.
homebridge-pihole_1  | Registering new address record for fe80::afd5:4dc4:16bf:ee5 on eth0.*.
homebridge-pihole_1  | Registering new address record for 192.168.1.15 on eth0.IPv4.

```
docker-compose.yml
```
version: '2'
services:
  homebridge-pihole:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
```
**Docker Start Command:**
```

docker-compose up -d

```
**Homebridge Config:**
```

{
    "bridge": {
        "name": "Homebridge-pihole",
        "username": "CC:22:3D:E3:CD:32",
        "port": 51828,
        "pin": "031-45-157"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [
        {
            "accessory": "DummySwitch",
            "name": "I'm Home",
            "stateful": true
        }
    ],
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": "8080",
            "sudo": "false"
        },
        {
            "platform": "Nest",
            "googleAuth": {
                "issueToken": "xxxxx",
                "cookies": "xxxxx",
                "apiKey": "xxxx"
            }
        },
        {
            "platform": "BelkinWeMo",
            "name": "WeMo Platform",
            "ignoredDevices": [
                "221604K1300B17",
                "221517K01005D8",
                "221616K1300FB0",
                "221604K1300879",
                "221335K0100CEB",
                "231550B010035F",
                "22A9B1K0108487",
                "221829K0108AB1"
            ]
        },
        {
            "platform": "yamaha-avr",
            "name": "Receiver",
            "ip": "192.168.1.67",
            "inputs": [
                {
                    "id": "HDMI1",
                    "name": "Apple TV"
                },
                {
                    "id": "HDMI3",
                    "name": "Switch"
                },
                {
                    "id": "AUDIO1",
                    "name": "TV"
                }
            ]
        },
        {
            "platform": "SmartThings",
            "name": "SmartThings",
            "app_url": "https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "xxxxxxxxxxxx",
            "access_token": "xxxxxxxxxxxxx"
        },
        {
            "platform": "Ring",
            "refreshToken": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
            "alarmOnEntryDelay": false,
            "hideCameraMotionSensor": true,
            "hideUnsupportedServices": true
        }
    ]
}


```

**Environment:**

* **Host Operating System**: Raspian
* **Docker Version**: 19.03.5

**Comment by oznu** [comment]
Hi @skbeez,

Try the `no-avahi` tag:

https://github.com/oznu/docker-homebridge/wiki#image-variants

**Comment by skbeez** [comment]
Here's what I got when I ran that:

```
pi@raspberrypi:~/homebridge $ docker run oznu/homebridge:debian-no-avahi
docker: Error response from daemon: failed to create endpoint loving_noyce on network bridge: failed to add the host (veth924b5e3) <=> sandbox (veth2225433) pair interfaces: operation not supported.
ERRO[0001] error waiting for container: context canceled 
pi@raspberrypi:~/homebridge $ 
```

**Comment by oznu** [comment]
Just change the tag in the `docker-compose.yml`:

```
version: '2'
services:
  homebridge-pihole:
    image: oznu/homebridge:no-avahi
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
```

And run:

```
docker-compose up -d
```

**Comment by skbeez** [comment]
Okay now here's what the logs say, looks like there's a few errors but I am not sure where they are coming from:

```
[1/28/2020, 12:43:29 AM] [SmartThings] SmartThings Hub Communication Established
[1/28/2020, 12:43:30 AM] [Ring] Creating location socket.io connection
[1/28/2020, 12:43:31 AM] [Ring] Ring connected to socket.io server
[1/28/2020, 12:43:31 AM] [Ring] Configuring 1 cameras and 20 devices for location "Melbourne" - locationId: dhyxsc-p3tq-0
[1/28/2020, 12:43:31 AM] [Ring] Hidden accessory adapter.zigbee ZigBee onboard adapter
[1/28/2020, 12:43:31 AM] [Ring] Hidden accessory access-code.vault Code Vault
[1/28/2020, 12:43:31 AM] [Ring] Hidden accessory access-code Security Access Code
[1/28/2020, 12:43:31 AM] [Ring] Hidden accessory hub.redsky Base Station
[1/28/2020, 12:43:31 AM] [Ring] Hidden accessory adapter.zwave Z-Wave Adapter
[1/28/2020, 12:43:31 AM] [Ring] Hidden accessory security-keypad Entryway Keypad
[1/28/2020, 12:43:31 AM] [Ring] Hidden accessory range-extender.zwave Family Room Range Extender
[1/28/2020, 12:43:31 AM] [Ring] Hidden accessory security-keypad Laundry Entryway Keypad
[1/28/2020, 12:43:31 AM] [Ring] Adding new accessory doorbell Front Door
[1/28/2020, 12:43:31 AM] Front Door is running on port 41867.
[1/28/2020, 12:43:31 AM] Please add [Front Door] manually in Home app. Setup Code: 031-45-157
[1/28/2020, 12:50:50 AM] Loaded config.json with 1 accessories and 6 platforms.
[1/28/2020, 12:50:50 AM] ---
[1/28/2020, 12:50:50 AM] Loaded plugin: homebridge-dummy
[1/28/2020, 12:50:50 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[1/28/2020, 12:50:50 AM] ---
[1/28/2020, 12:50:52 AM] Loaded plugin: homebridge-nest
[1/28/2020, 12:50:52 AM] Registering platform 'homebridge-nest.Nest'
[1/28/2020, 12:50:52 AM] ---
[1/28/2020, 12:50:53 AM] Loaded plugin: homebridge-platform-wemo
[1/28/2020, 12:50:53 AM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[1/28/2020, 12:50:53 AM] ---
[1/28/2020, 12:50:55 AM] [Config] Homebridge Config UI X v4.8.1 is listening on :: port 8081
[1/28/2020, 12:50:57 AM] Loaded plugin: homebridge-ring
[1/28/2020, 12:50:57 AM] Registering platform 'homebridge-ring.Ring'
[1/28/2020, 12:50:57 AM] ---
[1/28/2020, 12:50:59 AM] Loaded plugin: homebridge-smartthings-tonesto7
Homebridge Version: 2.4
[1/28/2020, 12:50:59 AM] Registering platform 'homebridge-smartthings.SmartThings'
[1/28/2020, 12:50:59 AM] ---
[1/28/2020, 12:51:01 AM] Loaded plugin: homebridge-yamaha-avr
[1/28/2020, 12:51:01 AM] Registering platform 'homebridge-yamaha-avr.yamaha-avr'
[1/28/2020, 12:51:01 AM] ---
[1/28/2020, 12:51:01 AM] Loaded plugin: homebridge-config-ui-x
[1/28/2020, 12:51:01 AM] Registering platform 'homebridge-config-ui-x.config'
[1/28/2020, 12:51:01 AM] ---
[1/28/2020, 12:51:01 AM] Loading 6 platforms...
[1/28/2020, 12:51:01 AM] [Config] Initializing config platform...
[1/28/2020, 12:51:01 AM] [Config] Running in Standalone Mode.
[1/28/2020, 12:51:01 AM] [Nest] Initializing Nest platform...
[1/28/2020, 12:51:01 AM] [Nest] Fetching Nest devices.
[1/28/2020, 12:51:01 AM] [WeMo Platform] Initializing BelkinWeMo platform...
[1/28/2020, 12:51:01 AM] [Receiver] Initializing yamaha-avr platform...
[1/28/2020, 12:51:01 AM] [Receiver] Initializing platform accessory 'Receiver'...
[1/28/2020, 12:51:02 AM] [SmartThings] Initializing SmartThings platform...
[1/28/2020, 12:51:02 AM] [SmartThings] Fetching SmartThings devices.
[1/28/2020, 12:51:02 AM] [Ring] Initializing Ring platform...
[1/28/2020, 12:51:02 AM] Loading 1 accessories...
[1/28/2020, 12:51:02 AM] [I'm Home] Initializing DummySwitch accessory...
[1/28/2020, 12:51:02 AM] [I'm Home] Setting switch to true
[1/28/2020, 12:51:02 AM] [Ring] Configuring cached accessory f47befd5-787c-4dc7-9345-6d7a9addb573 Ring Alarm
[1/28/2020, 12:51:02 AM] [Ring] Configuring cached accessory ffb1a126-40e1-46a1-b6ea-def8e41ace61 Front Door
[1/28/2020, 12:51:02 AM] [Ring] Configuring cached accessory 792a933a-ab93-4035-af35-31f5850530f0 Entryway
[1/28/2020, 12:51:02 AM] [Ring] Configuring cached accessory d1beafec-3196-4e03-89b2-652cb8d045c9 Family Room Motion
[1/28/2020, 12:51:02 AM] [Ring] Configuring cached accessory 8573e73a-38f8-48b4-8d9b-3d12ac9f84c2 Sliding Door
[1/28/2020, 12:51:02 AM] [Ring] Configuring cached accessory e8d4bbde-bfca-491e-a57a-3451402924e6 Kitchen Window
[1/28/2020, 12:51:02 AM] [Ring] Configuring cached accessory c8693d17-5cd4-4e73-bf87-9a075947cc1d Dining Window 2
[1/28/2020, 12:51:02 AM] [Ring] Configuring cached accessory 039e2dd2-bd06-4e6d-ad5d-fa1d20829216 Dining Window 1
[1/28/2020, 12:51:02 AM] [Ring] Configuring cached accessory 817c3799-2843-400b-be80-b35500c18ea0 Garage Entry
[1/28/2020, 12:51:02 AM] [Ring] Configuring cached accessory 530290ce-1cab-4d49-bdfb-055f2df068ed Master Window 1
[1/28/2020, 12:51:02 AM] [Ring] Configuring cached accessory ee61a664-7852-4864-a10f-01eb2a8c22bf Master Window 2
[1/28/2020, 12:51:02 AM] [Ring] Request for machine id timed out.  Falling back to random session id
[1/28/2020, 12:51:03 AM] [WeMo Platform] Online: Garage Door [94103ED38468]
[1/28/2020, 12:51:03 AM] [WeMo Platform] Garage Door - Get Current Door State: Closed
Unhandled rejection StatusCodeError: 401 - {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}
    at new StatusCodeError (/homebridge/node_modules/homebridge-nest/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/homebridge/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/homebridge/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/homebridge/node_modules/homebridge-nest/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-nest/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-nest/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[1/28/2020, 12:51:04 AM] [SmartThings] Unknown Capabilities: ["Health Check"]
[1/28/2020, 12:51:04 AM] [SmartThings] Initializing platform accessory 'Master Nightstand 1'...
[1/28/2020, 12:51:04 AM] [SmartThings] Initializing platform accessory 'Master Nightstand 2'...
[1/28/2020, 12:51:04 AM] [SmartThings] update_method: direct
[1/28/2020, 12:51:04 AM] [SmartThings] Direct Connect Is Listening On 192.168.1.19:8000
[1/28/2020, 12:51:04 AM] [SmartThings] SmartThings Hub Communication Established
[1/28/2020, 12:51:05 AM] [Ring] Creating location socket.io connection
[1/28/2020, 12:51:05 AM] [Ring] Ring connected to socket.io server
[1/28/2020, 12:51:06 AM] [Ring] Configuring 1 cameras and 20 devices for location "Melbourne" - locationId: dhyxsc-p3tq-0
[1/28/2020, 12:51:06 AM] [Ring] Hidden accessory adapter.zigbee ZigBee onboard adapter
[1/28/2020, 12:51:06 AM] [Ring] Hidden accessory access-code.vault Code Vault
[1/28/2020, 12:51:06 AM] [Ring] Hidden accessory access-code Security Access Code
[1/28/2020, 12:51:06 AM] [Ring] Hidden accessory hub.redsky Base Station
[1/28/2020, 12:51:06 AM] [Ring] Hidden accessory adapter.zwave Z-Wave Adapter
[1/28/2020, 12:51:06 AM] [Ring] Hidden accessory security-keypad Entryway Keypad
[1/28/2020, 12:51:06 AM] [Ring] Hidden accessory range-extender.zwave Family Room Range Extender
[1/28/2020, 12:51:06 AM] [Ring] Hidden accessory security-keypad Laundry Entryway Keypad
[1/28/2020, 12:51:06 AM] [Ring] Adding new accessory doorbell Front Door
[1/28/2020, 12:51:06 AM] Front Door is running on port 43263.
[1/28/2020, 12:51:06 AM] Please add [Front Door] manually in Home app. Setup Code: 031-45-157
[1/28/2020, 12:51:07 AM] Error: Service name is already in use on the network
    at Registry._onProbeComplete (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:106:27)
    at Prober.done (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
    at Prober.onMDNSresponse (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
    at EventEmitter.emit (events.js:223:5)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (events.js:223:5)
    at UDP.onMessage [as onmessage] (dgram.js:874:8)
[1/28/2020, 12:51:07 AM] Got SIGTERM, shutting down Homebridge...
[1/28/2020, 12:51:18 AM] Loaded config.json with 1 accessories and 6 platforms.
[1/28/2020, 12:51:18 AM] ---
[1/28/2020, 12:51:18 AM] Loaded plugin: homebridge-dummy
[1/28/2020, 12:51:18 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[1/28/2020, 12:51:18 AM] ---
[1/28/2020, 12:51:20 AM] Loaded plugin: homebridge-nest
[1/28/2020, 12:51:20 AM] Registering platform 'homebridge-nest.Nest'
[1/28/2020, 12:51:20 AM] ---
[1/28/2020, 12:51:20 AM] Loaded plugin: homebridge-platform-wemo
[1/28/2020, 12:51:20 AM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[1/28/2020, 12:51:20 AM] ---
[1/28/2020, 12:51:23 AM] Loaded plugin: homebridge-ring
[1/28/2020, 12:51:23 AM] Registering platform 'homebridge-ring.Ring'
[1/28/2020, 12:51:23 AM] ---
[1/28/2020, 12:51:25 AM] Loaded plugin: homebridge-smartthings-tonesto7
Homebridge Version: 2.4
[1/28/2020, 12:51:25 AM] Registering platform 'homebridge-smartthings.SmartThings'
[1/28/2020, 12:51:25 AM] ---
[1/28/2020, 12:51:26 AM] Loaded plugin: homebridge-yamaha-avr
[1/28/2020, 12:51:26 AM] Registering platform 'homebridge-yamaha-avr.yamaha-avr'
[1/28/2020, 12:51:26 AM] ---
[1/28/2020, 12:51:26 AM] Loaded plugin: homebridge-config-ui-x
[1/28/2020, 12:51:26 AM] Registering platform 'homebridge-config-ui-x.config'
[1/28/2020, 12:51:26 AM] ---
[1/28/2020, 12:51:26 AM] Loading 6 platforms...
[1/28/2020, 12:51:26 AM] [Config] Initializing config platform...
[1/28/2020, 12:51:26 AM] [Config] Running in Standalone Mode.
[1/28/2020, 12:51:26 AM] [Nest] Initializing Nest platform...
[1/28/2020, 12:51:26 AM] [Nest] Fetching Nest devices.
[1/28/2020, 12:51:27 AM] [WeMo Platform] Initializing BelkinWeMo platform...
[1/28/2020, 12:51:27 AM] [Receiver] Initializing yamaha-avr platform...
[1/28/2020, 12:51:27 AM] [Receiver] Initializing platform accessory 'Receiver'...
[1/28/2020, 12:51:27 AM] [SmartThings] Initializing SmartThings platform...
[1/28/2020, 12:51:27 AM] [SmartThings] Fetching SmartThings devices.
[1/28/2020, 12:51:27 AM] [Ring] Initializing Ring platform...
[1/28/2020, 12:51:27 AM] Loading 1 accessories...
[1/28/2020, 12:51:27 AM] [I'm Home] Initializing DummySwitch accessory...
[1/28/2020, 12:51:27 AM] [I'm Home] Setting switch to true
[1/28/2020, 12:51:27 AM] [Ring] Configuring cached accessory f47befd5-787c-4dc7-9345-6d7a9addb573 Ring Alarm
[1/28/2020, 12:51:27 AM] [Ring] Configuring cached accessory ffb1a126-40e1-46a1-b6ea-def8e41ace61 Front Door
[1/28/2020, 12:51:27 AM] [Ring] Configuring cached accessory 792a933a-ab93-4035-af35-31f5850530f0 Entryway
[1/28/2020, 12:51:27 AM] [Ring] Configuring cached accessory d1beafec-3196-4e03-89b2-652cb8d045c9 Family Room Motion
[1/28/2020, 12:51:27 AM] [Ring] Configuring cached accessory 8573e73a-38f8-48b4-8d9b-3d12ac9f84c2 Sliding Door
[1/28/2020, 12:51:27 AM] [Ring] Configuring cached accessory e8d4bbde-bfca-491e-a57a-3451402924e6 Kitchen Window
[1/28/2020, 12:51:27 AM] [Ring] Configuring cached accessory c8693d17-5cd4-4e73-bf87-9a075947cc1d Dining Window 2
[1/28/2020, 12:51:27 AM] [Ring] Configuring cached accessory 039e2dd2-bd06-4e6d-ad5d-fa1d20829216 Dining Window 1
[1/28/2020, 12:51:27 AM] [Ring] Configuring cached accessory 817c3799-2843-400b-be80-b35500c18ea0 Garage Entry
[1/28/2020, 12:51:27 AM] [Ring] Configuring cached accessory 530290ce-1cab-4d49-bdfb-055f2df068ed Master Window 1
[1/28/2020, 12:51:27 AM] [Ring] Configuring cached accessory ee61a664-7852-4864-a10f-01eb2a8c22bf Master Window 2
[1/28/2020, 12:51:27 AM] [Ring] Request for machine id timed out.  Falling back to random session id
[1/28/2020, 12:51:28 AM] [WeMo Platform] Online: Garage Door [94103ED38468]
[1/28/2020, 12:51:28 AM] [SmartThings] Unknown Capabilities: ["Health Check"]
[1/28/2020, 12:51:28 AM] [SmartThings] Initializing platform accessory 'Master Nightstand 1'...
[1/28/2020, 12:51:28 AM] [SmartThings] Initializing platform accessory 'Master Nightstand 2'...
[1/28/2020, 12:51:28 AM] [SmartThings] update_method: direct
[1/28/2020, 12:51:28 AM] [SmartThings] Direct Connect Is Listening On 192.168.1.19:8000
[1/28/2020, 12:51:28 AM] [WeMo Platform] Garage Door - Get Current Door State: Closed
Unhandled rejection StatusCodeError: 401 - {"error":{"code":401,"message":"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED"}}
    at new StatusCodeError (/homebridge/node_modules/homebridge-nest/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/homebridge/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/homebridge/node_modules/homebridge-nest/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/homebridge/node_modules/homebridge-nest/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-nest/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-nest/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[1/28/2020, 12:51:29 AM] [SmartThings] SmartThings Hub Communication Established
[1/28/2020, 12:51:29 AM] [Ring] Creating location socket.io connection
[1/28/2020, 12:51:30 AM] [Ring] Ring connected to socket.io server
[1/28/2020, 12:51:30 AM] [Ring] Configuring 1 cameras and 20 devices for location "Melbourne" - locationId: dhyxsc-p3tq-0
[1/28/2020, 12:51:30 AM] [Ring] Hidden accessory adapter.zigbee ZigBee onboard adapter
[1/28/2020, 12:51:30 AM] [Ring] Hidden accessory access-code.vault Code Vault
[1/28/2020, 12:51:30 AM] [Ring] Hidden accessory access-code Security Access Code
[1/28/2020, 12:51:30 AM] [Ring] Hidden accessory hub.redsky Base Station
[1/28/2020, 12:51:30 AM] [Ring] Hidden accessory adapter.zwave Z-Wave Adapter
[1/28/2020, 12:51:30 AM] [Ring] Hidden accessory security-keypad Entryway Keypad
[1/28/2020, 12:51:30 AM] [Ring] Hidden accessory range-extender.zwave Family Room Range Extender
[1/28/2020, 12:51:31 AM] [Ring] Hidden accessory security-keypad Laundry Entryway Keypad
[1/28/2020, 12:51:31 AM] [Ring] Adding new accessory doorbell Front Door
[1/28/2020, 12:51:31 AM] Front Door is running on port 37275.
[1/28/2020, 12:51:31 AM] Please add [Front Door] manually in Home app. Setup Code: 031-45-157
[1/28/2020, 12:52:18 AM] [Ring] Snapshot for Front Door Requested
[1/28/2020, 12:53:03 AM] [Ring] Snapshot failed to refresh after 60 attempts
[1/28/2020, 12:53:04 AM] [Ring] Snapshot for Front Door Received (45.709s)
```

**Comment by oznu** [comment]
```
[1/28/2020, 12:51:07 AM] Error: Service name is already in use on the network
```

Make sure the name of the bridge in the config.json is unique on your network. It looks like you also have issues with your wemo plugin, but that's out of scope for this issue.

**Comment by skbeez** [comment]
The no-avahi image fixed my original issue and there was an issue with my nest plugin for some reason. I copied and pasted my credentials back into my config file and that fixed my issue. Thank you again for your help!
