### ISSUE TITLE
Homebridge not starting anymore

### ISSUE THREAD

**Issue by KristjanBob** [oznu/docker-homebridge#301]
**Describe Your Problem:**

I am using Synology NAS to run Homebridge for Fibaro home automation. So I can control Fibaro switches and sockets with Apple Home.

Something happened with my homebride setup. It use to work very well and without any problems but starting from couple of days ago it won't start anymore. I don't understand the problem, perhaps somebody from here does. I didn't want to reset everything also since it's a big job to setup everything again :).

**Logs:**

2020-04-30 19:16:38,stdout,[37m[4/30/2020, 10:16:38 PM] [39m---
--
2020-04-30 19:16:38,stdout,[37m[4/30/2020, 10:16:38 PM] [39mLoaded config.json with 0 accessories and 1 platforms.
2020-04-30 19:16:37,stdout,[37m[4/30/2020, 10:16:37 PM][0m [36m[HB Supervisor][0m Started Homebridge v1.0.4 with PID: 9105
2020-04-30 19:16:37,stdout,[37m[4/30/2020, 10:16:37 PM][0m [36m[HB Supervisor][0m Starting Homebridge with extra flags: -P /homebridge/node_modules
2020-04-30 19:16:37,stdout,[37m[4/30/2020, 10:16:37 PM][0m [36m[HB Supervisor][0m Restarting Homebridge...
2020-04-30 19:16:32,stdout,[37m[4/30/2020, 10:16:32 PM][0m [36m[HB Supervisor][0m Homebridge Process Ended. Code: 0, Signal: null
2020-04-30 19:16:32,stdout,[31m    at Module._compile (internal/modules/cjs/loader.js:1133:30)[39m2020-04-30 19:16:32,stdout,[31m    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)[39m2020-04-30 19:16:32,stdout,[31m    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)[39m2020-04-30 19:16:32,stdout,[31m    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:148:10)[39m2020-04-30 19:16:32,stdout,[31m    at Server.loadCachedPlatformAccessoriesFromDisk (/usr/local/lib/node_modules/homebridge/src/server.ts:261:58)[39m2020-04-30 19:16:32,stdout,[31m    at Array.map (<anonymous>)[39m2020-04-30 19:16:32,stdout,[31m    at /usr/local/lib/node_modules/homebridge/src/server.ts:262:34[39m2020-04-30 19:16:32,stdout,[31m    at Function.deserialize (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:150:33)[39m2020-04-30 19:16:32,stdout,[31m    at Function.Accessory.deserialize (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1720:15)[39m2020-04-30 19:16:32,stdout,[31m    at Accessory._this._sideloadServices (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1047:17)[39m2020-04-30 19:16:32,stdout,[37m[4/30/2020, 10:16:32 PM] [39m[31mTypeError: Cannot read property 'getCharacteristic' of undefined[39m
2020-04-30 19:16:32,stdout,[37m[4/30/2020, 10:16:32 PM] [39m---
2020-04-30 19:16:32,stdout,[37m[4/30/2020, 10:16:32 PM] [39mLoaded config.json with 0 accessories and 1 platforms.
2020-04-30 19:16:31,stdout,[37m[4/30/2020, 10:16:31 PM][0m [36m[HB Supervisor][0m Started Homebridge v1.0.4 with PID: 9085
2020-04-30 19:16:31,stdout,[37m[4/30/2020, 10:16:31 PM][0m [36m[HB Supervisor][0m Starting Homebridge with extra flags: -P /homebridge/node_modules
2020-04-30 19:16:31,stdout,[37m[4/30/2020, 10:16:31 PM][0m [36m[HB Supervisor][0m Restarting Homebridge...
2020-04-30 19:16:26,stdout,[37m[4/30/2020, 10:16:26 PM][0m [36m[HB Supervisor][0m Homebridge Process Ended. Code: 0, Signal: null
2020-04-30 19:16:26,stdout,[31m    at Module._compile (internal/modules/cjs/loader.js:1133:30)[39m2020-04-30 19:16:26,stdout,[31m    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)[39m2020-04-30 19:16:26,stdout,[31m    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)[39m2020-04-30 19:16:26,stdout,[31m    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:148:10)[39m2020-04-30 19:16:26,stdout,[31m    at Server.loadCachedPlatformAccessoriesFromDisk (/usr/local/lib/node_modules/homebridge/src/server.ts:261:58)[39m2020-04-30 19:16:26,stdout,[31m    at Array.map (<anonymous>)[39m2020-04-30 19:16:26,stdout,[31m    at /usr/local/lib/node_modules/homebridge/src/server.ts:262:34[39m2020-04-30 19:16:26,stdout,[31m    at Function.deserialize (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:150:33)[39m2020-04-30 19:16:26,stdout,[31m    at Function.Accessory.deserialize (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1720:15)[39m2020-04-30 19:16:26,stdout,[31m    at Accessory._this._sideloadServices (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1047:17)[39m2020-04-30 19:16:26,stdout,[37m[4/30/2020, 10:16:26 PM] [39m[31mTypeError: Cannot read property 'getCharacteristic' of undefined[39m
**Docker Start Command:**

**Homebridge Config:**

{
    "bridge": {
        "name": "Homebridge D787",
        "username": "0E:AB:6B:F2:D7:87",
        "port": 51826,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "FibaroHC2",
            "name": "HC2",
            "host": "192.168.1.xx",
            "username": "e-mail",
            "password": "psw",
            "pollerperiod": "2",
            "securitysystem": "enabled",
            "switchglobalvariables": "PUT A COMMA SEPARATED LIST OF HOME CENTER GLOBAL VARIABLES ACTING LIKE A BISTABLE SWITCH",
            "thermostattimeout": "7200",
            "enablecoolingstatemanagemnt": "on",
            "doorlocktimeout": "0",
            "IFTTTmakerkey": "PUT KEY OF YOUR MAKER CHANNEL HERE (USED TO SIGNAL EVENTS TO THE OUTSIDE)",
            "enableIFTTTnotification": "none",
            "LockCurrentStateDelay": "PUT THE NUMBER OF SECONDS (DEFAULT 2) TO DELAY THE UPDATE OF LockCurrentState READ EVENT",
            "LockTargetStateDelay": "PUT THE NUMBER OF SECONDS (DEFAULT 2) TO DELAY THE UPDATE OF LockTargetState READ EVENT"
        }
    ]
}`

**Screenshots:**

**Environment:**
* **Synology - Fibaro - Apple Home
* **Host Operating System**: Synology NAS version DSM 6.2.2-24922 Update 4
* **Docker Version**: 18.09.0-0506
* **Homebridge Docker version 1.0.7 (oznu)

![Screenshot 2020-05-01 at 19 45 38](https://user-images.githubusercontent.com/64609912/80822939-5f8b7200-8be4-11ea-8691-336a028db2ae.png)

**Comment by Lesix69** [comment]
I've got exactly the same issue after upgrading my container to the latest version couple days ago.
Also using Synology DSM and Fibaro HC2 plugin.

**Comment by KristjanBob** [comment]
Ok, is it possible to downgrade to the working version or what is the solution then?

**Comment by oznu** [comment]
You can rollback to 0.4.53 by running this in the web terminal / inside the container:


```
npm install -g homebridge@0.4.53
```

If you want that to persist through container updates / recreation add that to the `startup.sh` file.

**Comment by KristjanBob** [comment]
Thank you oznu! Or is there a better solution to get it to work with new container software?

**Comment by KristjanBob** [comment]
> You can rollback to 0.4.53 by running this in the web terminal / inside the container:
> 
> ```
> npm install -g homebridge@0.4.53
> ```
> 
> If you want that to persist through container updates / recreation add that to the `startup.sh` file.

Hi,

I did the rollback but nothing changed. I don't understand what is the problem?

Kristjan

**Comment by KristjanBob** [comment]
> I've got exactly the same issue after upgrading my container to the latest version couple days ago.
> Also using Synology DSM and Fibaro HC2 plugin.

Hi, did you get yours working?

**Comment by Lesix69** [comment]
I was able to fix the problem.
1. Removed all plugins and accessories from config.json, package.json, startup.sh, the only line in startup.sh was "npm install -g homebridge@0.4.53"
2. Cleared persist folder
3. Removed cachedAccessories from accessories folder
4. Created a new container based on duplicated settings
5. Homebridge was started OK with version 0.4.53
6. Reverted back all the config files to the previous settings, modified startup.sh to install latest homebridge version "npm install -g homebridge"
7. Homebridge was updated to ver. 1.0.4 and started OK

I think the problem was with some cached accessories, at least in my case.

**Comment by allwyn007** [comment]
i had this same issue and after following the steps you proposed now issue is solved

**Comment by allwyn007** [comment]
@KristjanBob @oznu  i am also having an issue with my homebridge which i am using to control fibaro through homekit. whenever fibaro homecenter lite restarts, i have to restart the homebridge(raspberry pi) inorder to work normally... is there a way to automate homebridge in such a way that after the fibaro restart homebridge sholud restart after certain minutes... waiting for your response...

**Comment by KristjanBob** [comment]
Hi,

I have a problem with my Homebridge Fibaro setup on Synology NAS. Can you please help me what could be wrong?

I have:
Synology NAS DS918+ on DSM 7.0-41890
Home Center 2 on 4.630

It shows the following error:
[9/28/2023, 9:07:24 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge) is running on port 51826.
[9/28/2023, 9:07:25 PM] [FibaroHC] Launched child bridge with PID 18354
[9/28/2023, 9:07:25 PM] Registering platform 'homebridge-fibaro-home-center.FibaroHC'
[9/28/2023, 9:07:25 PM] [FibaroHC] Loaded homebridge-fibaro-home-center v1.2.20 child bridge successfully
[9/28/2023, 9:07:25 PM] Loaded 0 cached accessories from cachedAccessories.0E321E4197C7.
[9/28/2023, 9:07:25 PM] [FibaroHC] Cannot find ca.cer in:  /volume1/homebridge
[9/28/2023, 9:07:25 PM] [FibaroHC] Put a valid ca.cer file in config.json folder.
[9/28/2023, 9:07:25 PM] [FibaroHC] Cannot connect to Fibaro Home Center. Check credentials, url/host or ca.cer file
[9/28/2023, 9:07:25 PM] Homebridge v1.6.1 (HAP v0.11.1) (FibaroHC) is running on port 47164.

I have installed the following plugins:
Homebridge UI 
homebridge-config-ui-x v4.50.6

homebridge Fibaro Home Center 
homebridge-fibaro-home-center v1.2.20

What more information do you need?

Best regards,

Kristjan

**Comment by NorthernMan54** [comment]
@KristjanBob I'm not familiar with FibaroHC, but it looks like the plugin is looking for `a valid ca.cer file`
