### ISSUE TITLE
Plugin not uninstalled correctly

### ISSUE THREAD

**Issue by AlfaJackal** [oznu/docker-homebridge#316]
I have homebridge-netatmo as a plugin installed. I uninstalled it via GUI > Plugins but the entry remains there after receiving the message „successfully uninstalled“. 
My config.json is clean, no homebridge-netatmo configured.

After rebooting, I receive this error message:
```

[6/29/2020, 10:46:04 PM] ====================
[6/29/2020, 10:46:04 PM] ERROR LOADING PLUGIN homebridge-netatmo:
[6/29/2020, 10:46:04 PM] Error: Cannot find module 'async'
Require stack:
- /homebridge/node_modules/homebridge-netatmo/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-netatmo/index.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
[6/29/2020, 10:46:04 PM] ====================
```
How can I get rid of this plugin? 
After restarting the entire container, the error message disappears, but homebridge-netatmo still remains as a plugin.

—
Running on docker, Rpi 4, latest image.

**Comment by oznu** [comment]
Inside the container run:

```
rm -rf /homebridge/node_modules/homebridge-netatmo
```
