### ISSUE TITLE
Adding local custom accessory

### ISSUE THREAD

**Issue by stevemac00** [oznu/docker-homebridge#322]
**Describe Your Problem:**
I have been using successfully for over a year with a custom platform. Now, I want to add a custom accessory locally. I duplicated dummy-switch, changed the names and placed the new directory at the root level.

Maybe my brain has fried but it seems I should be able to add a local custom accessory just as I successfully did with the platform. Below, the references "homebridge-ssmotion" is the new custom accessory and  "homebridge-secmon" is the platform which worked fine.

Looking for any ideas (or insults). Thanks for maintaining the docker image.

**Logs:**

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:493:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at LocalStorage.parseDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:637:35)
    at LocalStorage.parseDataDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
    at Object.init (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:31:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
```

**Docker Start Command:**
```
docker run --net=host --detach  --name homebridge -e TZ=America/Chicago -e PGID=100 -e PUID=1026 --volume /volume1/docker/homebridge/:/homebridge oznu/homebridge
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "accessories": [
        {
        "accessory": "DummySwitch",
        "name": "My Switch"
        },
        {
        "accessory": "SSMotionSwitch",
        "name": "HomeSwitch",
        "stateful": true
        }
        ],

    "platforms": [
        {
            "platform": "Secmon",
            "statusServerHost": "http://10.0.1.25",
            "statusServerPort": 8115,
            "statusServerToken": "servertoken",
            "secmonHost" : "http://10.0.1.25:8112",
            "secmonRegisterPath" : "/api/homekit/register/callback",
            "secmonAlarmPath" : "/api/homekit/alarm/setstate",
            "devices": [
              {
                "type": "SecuritySystem",
                "id": "securitysystem",
                "name": "Alarm System"
              }
            ]
        }        
      ]}
```

**Additional**
* **startup.sh**
```
npm install homebridge-secmon
npm install homebridge-ssmotion
```
* **/package.json**
```
{
  "dependencies": {
    "homebridge-dummy": "^0.2.0",
    "homebridge-secmon": "file:homebridge-secmon",
    "homebridge-ssmotion": "file:homebridge-ssmotion"
  }
}
```

**Environment:**
* **Host Operating System**: Synology
* **Docker Version**: 
* **Image Tag / Type**: No tag

**Comment by stevemac00** [comment]
I reverted homebridge directory from snapshot and repeated same steps (as above) and it worked fine. I wonder if it could've been synology directories like @eaDir?
