### ISSUE TITLE
Python errors during docker start 

### ISSUE THREAD

**Issue by chrisswanda** [oznu/docker-homebridge#330]
**Describe Your Problem:**
Homebridge docker instance stopped working a week or so ago, and I decided to just to teardown and redo everything.  When spinning up a brand new docker instance on my RPi, I am getting the below python errors during startup.  Not sure if this is part of a larger problem that others are reporting for Homebridge, but wanted to note this anyways in case it helps.

**Logs:**
```
homebridge_1  | [cont-init.d] 10-adduser: exited 0.
homebridge_1  | [cont-init.d] 20-set-timezone: executing...
homebridge_1  | Process Process-2:
homebridge_1  | Traceback (most recent call last):
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
homebridge_1  |     h.request(req.get_method(), req.selector, req.data, headers,
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 1255, in request
homebridge_1  |     self._send_request(method, url, body, headers, encode_chunked)
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
homebridge_1  |     self.endheaders(body, encode_chunked=encode_chunked)
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
homebridge_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
homebridge_1  |     self.send(msg)
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 950, in send
homebridge_1  |     self.connect()
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 1417, in connect
homebridge_1  |     super().connect()
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 921, in connect
homebridge_1  |     self.sock = self._create_connection(
homebridge_1  |   File "/usr/lib/python3.8/socket.py", line 808, in create_connection
homebridge_1  |     raise err
homebridge_1  |   File "/usr/lib/python3.8/socket.py", line 796, in create_connection
homebridge_1  |     sock.connect(sa)
homebridge_1  | ConnectionRefusedError: [Errno 111] Connection refused
homebridge_1  |
homebridge_1  | During handling of the above exception, another exception occurred:
homebridge_1  |
homebridge_1  | Traceback (most recent call last):
homebridge_1  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
homebridge_1  |     self.run()
homebridge_1  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
homebridge_1  |     self._target(*self._args, **self._kwargs)
homebridge_1  |   File "/usr/lib/python3.8/site-packages/tzupdate.py", line 84, in get_timezone_for_ip
homebridge_1  |     api_response_obj = urlopen(api_url)  # nosec
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
homebridge_1  |     return opener.open(url, data, timeout)
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 525, in open
homebridge_1  |     response = self._open(req, data)
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
homebridge_1  |     result = self._call_chain(self.handle_open, protocol, protocol +
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
homebridge_1  |     result = func(*args)
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
homebridge_1  |     return self.do_open(http.client.HTTPSConnection, req,
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
homebridge_1  |     raise URLError(err)
homebridge_1  | urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
homebridge_1  | Process Process-3:
homebridge_1  | Traceback (most recent call last):
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
homebridge_1  |     h.request(req.get_method(), req.selector, req.data, headers,
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 1255, in request
homebridge_1  |     self._send_request(method, url, body, headers, encode_chunked)
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
homebridge_1  |     self.endheaders(body, encode_chunked=encode_chunked)
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
homebridge_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
homebridge_1  |     self.send(msg)
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 950, in send
homebridge_1  |     self.connect()
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 1417, in connect
homebridge_1  |     super().connect()
homebridge_1  |   File "/usr/lib/python3.8/http/client.py", line 921, in connect
homebridge_1  |     self.sock = self._create_connection(
homebridge_1  |   File "/usr/lib/python3.8/socket.py", line 808, in create_connection
homebridge_1  |     raise err
homebridge_1  |   File "/usr/lib/python3.8/socket.py", line 796, in create_connection
homebridge_1  |     sock.connect(sa)
homebridge_1  | OSError: [Errno 101] Network unreachable
homebridge_1  |
homebridge_1  | During handling of the above exception, another exception occurred:
homebridge_1  |
homebridge_1  | Traceback (most recent call last):
homebridge_1  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
homebridge_1  |     self.run()
homebridge_1  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
homebridge_1  |     self._target(*self._args, **self._kwargs)
homebridge_1  |   File "/usr/lib/python3.8/site-packages/tzupdate.py", line 84, in get_timezone_for_ip
homebridge_1  |     api_response_obj = urlopen(api_url)  # nosec
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
homebridge_1  |     return opener.open(url, data, timeout)
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 525, in open
homebridge_1  |     response = self._open(req, data)
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
homebridge_1  |     result = self._call_chain(self.handle_open, protocol, protocol +
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
homebridge_1  |     result = func(*args)
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
homebridge_1  |     return self.do_open(http.client.HTTPSConnection, req,
homebridge_1  |   File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
homebridge_1  |     raise URLError(err)
homebridge_1  | urllib.error.URLError: <urlopen error [Errno 101] Network unreachable>
homebridge_1  | Set system timezone to America/Chicago.
homebridge_1  | [cont-init.d] 20-set-timezone: exited 0.
homebridge_1  | [cont-init.d] 30-packages: executing...
homebridge_1  | [cont-init.d] 30-packages: exited 0.
homebridge_1  | [cont-init.d] 40-dbus-avahi: executing...
homebridge_1  | [cont-init.d] 40-dbus-avahi: exited 0.
homebridge_1  | [cont-init.d] 45-user-data: executing...
homebridge_1  | [cont-init.d] 45-user-data: exited 0.
homebridge_1  | [cont-init.d] 50-plugins: executing...
```

**Docker Start Command:**

```
docker-compose up -d && docker-compose logs -f
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge D622",
        "username": "0E:BB:22:34:D6:22",
        "port": 51996,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        }
    ]
}
```

**Screenshots:**
https://i.imgur.com/evsBNrF.png

**Environment:**

* **Host Operating System**: Raspbian
* **Docker Version**: Docker version 19.03.13, build 4484c46
* **Image Tag / Type**: Alpine

**Comment by blu-e-man** [comment]
Have the same issue. 
Running on a Raspberry Pi with Docker.
