### ISSUE TITLE
Error: The requested platform 'hihomekit' was not registered by any plugin --  after upgrade to latest homebridge

### ISSUE THREAD

**Issue by hihipto** [oznu/docker-homebridge#331]
**Describe Your Problem:**
Homebridge was working fine for some months using custom plugin hihomekit (https://github.com/hihipto/hihomekit).
After upgrade to latest build, the system has issues loading the plugin platform.
Even after fresh install running in the same problem, not registering the platform.

**Logs:**

```
[10/2/2020, 8:43:39 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[10/2/2020, 8:43:39 PM] [HB Supervisor] Started Homebridge v1.2.3 with PID: 853
[10/2/2020, 8:43:51 PM] Loaded config.json with 0 accessories and 2 platforms.
[10/2/2020, 8:43:51 PM] ---
[10/2/2020, 8:44:01 PM] Loaded plugin: homebridge-config-ui-x@4.28.0
[10/2/2020, 8:44:01 PM] Registering platform 'homebridge-config-ui-x.config'
[10/2/2020, 8:44:01 PM] ---
[10/2/2020, 8:44:01 PM] Loading 2 platforms...
[10/2/2020, 8:44:01 PM] Error loading platform requested in your config.json at position 1
[10/2/2020, 8:44:04 PM] Error: The requested platform 'hihomekit' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
[10/2/2020, 8:44:05 PM] [HB Supervisor] Homebridge Process Ended. Code: 0, Signal: null
[10/2/2020, 8:44:10 PM] [HB Supervisor] Restarting Homebridge...
```

**Docker Start Command:**

```
docker run --net=host ...
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Willowstreet",
        "username": "CA:FF:77:34:56:77",
        "port": 51827,
        "pin": "123-45-678"
    },
    "accessories": [],
    "platforms": [
            {
            "platform": "hihomekit",
            "name": "Loxone",
            "host": "10.0.xx.xx",
            "port": "80",
            "username": "User",
            "password": "Pasw"
        },
        {
            "name": "Config",
            "port": 8080,
            "platform": "config"
        }
    ]
}
```

**Homebridge Package:**

```json
{
  "private": true,
  "description": "This file keeps track of which plugins should be installed.",
  "dependencies": {
    "hihomekit": "^1.1.3"
  }
}

```

**Screenshots:**

**Environment:**

* **Host Operating System**: Synology
* **Docker Version**: 18.09.0-0513
* **Image Tag / Type**: ENABLE_AVAHI=0 / QEMU_ARCH=x86_64

OS: Alpine Linux:  (3.12.0)
Hostname: Homebridge20201002 -- however this should be DS812 according the Environment Variables configured in DSM/docker app
Node.js Version: v12.18.4
Homebirdge Version: 1.2.3
Config_UI_version: 4.27.2
Npm Version: v6.14.6
User: root
Storage Path: /homebridge
Config Path: /homebridge/config.json
Plugin Path: /homebridge/node_modules
Docker: Yes
Service Mode: Yes

<img width="674" alt="image" src="https://user-images.githubusercontent.com/5295141/94960469-3e141680-04f3-11eb-9a46-4a0a822c9ebf.png">

<img width="393" alt="image" src="https://user-images.githubusercontent.com/5295141/94960532-584df480-04f3-11eb-8ea4-24d1d1492dec.png">

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/5295141/94960699-9c40f980-04f3-11eb-93a4-460f8d8375c1.png">

**Comment by oznu** [comment]
`hihomekit` is not a valid plugin name. Homebridge plugins are prefixed with "homebridge-".

Have you installed the correct plugin?

**Comment by hihipto** [comment]
@oznu thanks for the swift reply,
I've renamed my plugin to "homebridge-hihomekit" without success, I've the same error:

`[10/4/2020, 11:13:01 PM] [HB Supervisor] Restarting Homebridge...                                                                                  
[10/4/2020, 11:13:01 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules                                      
[10/4/2020, 11:13:01 PM] [HB Supervisor] Started Homebridge v1.2.3 with PID: 510                                                                   
[10/4/2020, 11:13:17 PM] Loaded config.json with 0 accessories and 2 platforms.                                                                    
[10/4/2020, 11:13:17 PM] ---                                                                                                                       
[10/4/2020, 11:13:27 PM] Loaded plugin: homebridge-config-ui-x@4.28.0                                                                              
[10/4/2020, 11:13:27 PM] Registering platform 'homebridge-config-ui-x.config'                                                                      
[10/4/2020, 11:13:27 PM] ---                                                                                                                       
[10/4/2020, 11:13:27 PM] Loading 2 platforms...                                                                                                    
[10/4/2020, 11:13:27 PM] Error loading platform requested in your config.json at position 1                                                        
[10/4/2020, 11:13:32 PM] Error: The requested platform 'homebridge-hihomekit' was not registered by any plugin.                                    
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)                                     
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37                                                                                 
    at Array.forEach (<anonymous>)                                                                                                                 
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)                                                          
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)                                                                  
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)                                                                               
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)                                                            
    at Module._compile (internal/modules/cjs/loader.js:1137:30)                                                                                    
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)                                                                      
    at Module.load (internal/modules/cjs/loader.js:985:32)                                                                                         
[10/4/2020, 11:13:32 PM] [HB Supervisor] Homebridge Process Ended. Code: 0, Signal: null     `
