### ISSUE TITLE
Running as root

### ISSUE THREAD

**Issue by mneumark** [oznu/docker-homebridge#49]
I'm trying to run homebridge-amazondash. It requires homebridge to be run as root to work, so I cannot get it to work with this docker image. Any thoughts on how to get this one working?

I'm getting the following in my log. I tried looking for alternative plugins but they all require root.
```
Error: socket: Operation not permitted
    at new PcapSession (/homebridge/node_modules/pcap/pcap.js:49:39)
    at Object.exports.createSession (/homebridge/node_modules/pcap/pcap.js:123:12)
    at create_session (/homebridge/node_modules/node-dash-button/index.js:24:28)
    at register (/homebridge/node_modules/node-dash-button/index.js:47:24)
    at DashPlatform.didFinishLaunching (/homebridge/node_modules/homebridge-amazondash/index.js:57:17)
    at emitNone (events.js:106:13)
    at API.emit (events.js:208:7)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:98:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Failed to create pcap session: couldn't find devices to listen on.
Try running with elevated privileges via 'sudo'
/homebridge/node_modules/node-dash-button/index.js:28
        throw new Error('Error: No devices to listen');
        ^

Error: Error: No devices to listen
    at create_session (/homebridge/node_modules/node-dash-button/index.js:28:15)
    at register (/homebridge/node_modules/node-dash-button/index.js:47:24)
    at DashPlatform.didFinishLaunching (/homebridge/node_modules/homebridge-amazondash/index.js:57:17)
    at emitNone (events.js:106:13)
    at API.emit (events.js:208:7)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:98:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.
```

**Comment by oznu** [comment]
Setting the `PUID` and `PGID` variables to `0` will run the homebridge process as `root`:

```
docker run --net=host -e PUID=0 -e PGID=0 oznu/homebridge
```

**Comment by mneumark** [comment]
Sweet! That fixed it. Thanks a lot!

**Comment by vinnyfiore** [comment]
@oznu Sorry to dredge up an old issue, but I have an issue using the same plugin. I found that manually changing the PGID and PUID in the docker-compose.yml both to 0 doesn't seem to actually affect the process.  In the logs it shows "User uid: 1000" and "User gid: 1000." This means I'm not able to actually get root access in the container. Is this something to do with docker-compose? Is there another way I should be doing it? I'm on Raspberry Pi if that makes any difference.

**Comment by oznu** [comment]
Did you run `docker-compose up -d` after changing the PGID and PUID in the docker-compose file? 

```yml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest  # use "raspberry-pi" instead of "latest" for arm devices
    restart: always
    network_mode: host
    environment:
      - PGID=0
      - PUID=0
    volumes:
      - ./volumes/homebridge:/homebridge
```
