### ISSUE TITLE
Permission Error on NPM Config

### ISSUE THREAD

**Issue by tankbusta** [oznu/docker-homebridge#51]
Hi,

I'm getting an endless loop of this error using the latest version.

```┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at LocalStorage.parseDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:637:35)
    at LocalStorage.parseDataDirSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:572:21)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/local-storage.js:145:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/node-persist/src/node-persist.js:41:29)
    at Object.init (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:29:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:24:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)```
```

If I drop to a shell inside the container, `/root/.config` is owned by abc/abc which is odd and i'm not sure why. I do have PUID and PGID set to the output of my synology NAS user (which has R/W to /homebridge) and as far as I can tell, all the files in /homebridge have the proper permissions as well.

Any ideas? Thanks!

**Comment by oznu** [comment]
The npm update check should not be crashing the process.  If shell into the container and delete the `/root/.config` folder this should make the npm warning go away, but it won't fix the problem.

```
EISDIR: illegal operation on a directory, read
```

EISDIR means Homebridge is trying to read it's config from what should be a file, but is actually a directory. Which is pretty strange. 

Can you try stopping homebridge,  delete the `/homebridge/persist` and `/homebridge/accessories` directories entirely and then recreate the container?

**Comment by tankbusta** [comment]
Sorry about this - I was moving from a Raspberry PI install to Synology/Docker and copied over `accessories/` and `persist/` and I guess something happened and/or one of the .json files had a reference to an old file path? 

Anyways, a clean install and replacing the old bridge fixed it.
