### ISSUE TITLE
Error - Homebridge on my Synology NAS

### ISSUE THREAD

**Issue by MSDaytona** [oznu/docker-homebridge#53]
Having followed the set-up to the dot I am getting when starting the container the following error
message.
Being a novice I am not sure where to lock to get this resolved.

[2018-1-20 16:18:01] Loaded plugin: homebridge-dummy
[2018-1-20 16:18:01] Registering accessory 'homebridge-dummy.DummySwitch'
[2018-1-20 16:18:01] ---
[2018-1-20 16:18:02] Loaded plugin: homebridge-platform-wemo
[2018-1-20 16:18:02] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[2018-1-20 16:18:02] ---
[2018-1-20 16:18:02] Loaded plugin: homebridge-config-ui-x
[2018-1-20 16:18:02] Registering platform 'homebridge-config-ui-x.config'
[2018-1-20 16:18:02] ---
[2018-1-20 16:18:02] Loaded config.json with 3 accessories and 0 platforms.
[2018-1-20 16:18:02] ---
[2018-1-20 16:18:02] Loading 0 platforms...
[2018-1-20 16:18:02] Loading 3 accessories...

/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
            ^
Error: The requested accessory 'Guest room' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:264:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

**Comment by oznu** [comment]
The error here is:

```
Error: The requested accessory 'Guest room' was not registered by any plugin.
```

Please check your config.json file.

**Comment by MSDaytona** [comment]
Thats what I thought as well but I can't discover anything:

{
    "bridge": {
        "name": "WeMoDevices",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-153"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Guest room"
        },
        {
            "accessory": "WeMo",
            "name": "Living Room"
        },
        {
            "accessory": "WeMo",
            "name": "Outdoor Lights"
        }
    ],

    "platforms": [

    ]

**Comment by oznu** [comment]
It looks like you are using the config for  [homebridge-wemo](https://www.npmjs.com/package/homebridge-wemo) but have the [homebridge-platform-wemo](https://www.npmjs.com/package/homebridge-platform-wemo) plugin installed.

I use the awesome [homebridge-platform-wemo](https://www.npmjs.com/package/homebridge-platform-wemo) plugin and my config just looks like this:

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "accessories": [
    ],
    "platforms": [
        {
            "platform": "BelkinWeMo",
            "name": "WeMo Platform"
        }
    ]
}
```

**Comment by MSDaytona** [comment]
Yep you are right with your assumption.
But I have three WeMo devices. 
Would your config work ? 
Do I not have to configure them in the "accessories" section of the file ?

**Comment by oznu** [comment]
The [homebridge-platform-wemo](https://www.npmjs.com/package/homebridge-platform-wemo) plugin will discover the WeMo devices on your local network and will register the accessories for you.
