### ISSUE TITLE
Plugins do not install on image update

### ISSUE THREAD

**Issue by mneumark** [oznu/docker-homebridge#55]
When I upgrade to the latest docker image,  I get an error that a plugin i installed does not exist. It shows up in the list of plugins in the web GUI, so I use that GUI to delete the plugin and then re-install it and then everything works. But this happens every time there is a new version of the docker image and I was wondering if there would be a more permanent fix to this.

**Comment by oznu** [comment]
I'm not sure why this would be happening. The UI app uses more or less the same code for plugin discovery that Homebridge uses. I test the image on my own permanent (not dev) setup after every release and have never had to reinstall the plugins as you describe.

Which plugins are you using out of interest? The only thing I can think of is the [way I remove plugins no longer listed in the package.json](https://github.com/oznu/docker-homebridge/blob/master/root/etc/cont-init.d/50-plugins#L5) might be causing issues, but this would be cause problems every time the container restarts - not just when a new image is pulled down.

**Comment by mneumark** [comment]
At the moment the only plugin I have is [amazondash](https://www.npmjs.com/package/homebridge-amazondash). This is the one that disappears when I update the container.

**Comment by oznu** [comment]
I can replicate the issue with that plugin.

I assume you are already starting the container with the `libpcap-dev` package defined:

```
docker run -e "PACKAGES=libpcap-dev" oznu/homebridge
```

If you add this line to the bottom of the [`/homebridge/startup.sh`](https://github.com/oznu/docker-homebridge/blob/master/root/defaults/startup.sh) file it will fix everything up every time the container is restarted/updated:

```
npm rebuild
```

**Comment by mneumark** [comment]
yup. I will give that a shot. Thanks.

**Comment by mneumark** [comment]
Yes, that is essentially what my call to docker looks like (with some other stuff too.

I just added `npm rebuild` and updated today and that didn't fix it. I do have the amazondash plugin set up in the startup.sh too as: `yarn add homebridge-amazondash`. See the below logs for the error:
```
ErrorWarningSystemArrayLogin


oauth-sign@0.8.2 /homebridge/node_modules/oauth-sign
performance-now@2.1.0 /homebridge/node_modules/performance-now
qs@6.5.1 /homebridge/node_modules/qs
safe-buffer@5.1.1 /homebridge/node_modules/safe-buffer
stringstream@0.0.5 /homebridge/node_modules/stringstream
tough-cookie@2.3.3 /homebridge/node_modules/tough-cookie
punycode@1.4.1 /homebridge/node_modules/punycode
tunnel-agent@0.6.0 /homebridge/node_modules/tunnel-agent
uuid@3.2.1 /homebridge/node_modules/uuid
bcrypt-pbkdf@1.0.1 /homebridge/node_modules/bcrypt-pbkdf
tweetnacl@0.14.5 /homebridge/node_modules/tweetnacl
ecc-jsbn@0.1.1 /homebridge/node_modules/ecc-jsbn
jsbn@0.1.1 /homebridge/node_modules/jsbn
[cont-init.d] 45-user-data: exited 0.
[cont-init.d] 50-plugins: executing...
Homebridge: Installing plugins...
npm WARN lifecycle socketwatcher@0.3.0~install: cannot run in wd %s %s (wd=%s) socketwatcher@0.3.0 node-gyp rebuild node_modules/socketwatcher
npm WARN lifecycle pcap@2.0.0~install: cannot run in wd %s %s (wd=%s) pcap@2.0.0 node-gyp rebuild node_modules/pcap
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No license field.

removed 1 package and updated 59 packages in 2.255s
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No license field.

up to date in 0.623s
[cont-init.d] 50-plugins: exited 0.
[cont-init.d] 55-config-ui: executing...
Enabling homebridge-config-ui-x...
[cont-init.d] 55-config-ui: exited 1.
[cont-init.d] done.
[services.d] starting services
Starting dbus-daemon
dbus[709]: [system] org.freedesktop.DBus.Error.AccessDenied: Failed to set fd limit to 65536: Operation not permitted

[services.d] done.
[2018-2-2 18:54:02] [homebridge-config-ui-x] Using Form Authentication
[2018-2-2 18:54:02] [homebridge-config-ui-x] Console is listening on port 8090.
Starting Avahi daemon
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.6.32 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!

Loading service file /etc/avahi/services/sftp-ssh.service.
Loading service file /etc/avahi/services/ssh.service.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***

Joining mDNS multicast group on interface virbr0.IPv4 with address 192.168.122.1.
New relevant interface virbr0.IPv4 for mDNS.
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface br0.IPv4 with address 10.0.1.2.
New relevant interface br0.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::1881:aeff:fee9:6916 on veth4f112d9.*.
Registering new address record for fe80::70fd:aaff:fe89:d00c on vethef0b4bb.*.
Registering new address record for fe80::940b:2aff:feba:e20e on vethbbb031b.*.
Registering new address record for fe80::58fa:2dff:fe95:5def on vetha275669.*.
Registering new address record for fe80::10ce:ccff:fe91:9ddd on veth832a7fd.*.
Registering new address record for 192.168.122.1 on virbr0.IPv4.
Registering new address record for fe80::fc36:11ff:fe12:4786 on veth4351e68.*.
Registering new address record for fe80::7829:3fff:fe7d:e194 on vethaed311a.*.
Registering new address record for fe80::42:69ff:fe15:ef52 on docker0.*.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::1cdf:4bff:fe0a:d557 on br0.*.
Registering new address record for 10.0.1.2 on br0.IPv4.
Registering new address record for fe80::225:90ff:feb5:62da on bond0.*.
Server startup complete. Host name is grumpNAS.local. Local service cookie is 3000267356.
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

[2018-2-2 18:54:07] ====================
[2018-2-2 18:54:07] ERROR LOADING PLUGIN homebridge-amazondash:

[2018-2-2 18:54:07] Error: Cannot find module './build/Release/pcap_binding'

at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/homebridge/node_modules/pcap/pcap.js:3:21)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
[2018-2-2 18:54:07] ====================
[2018-2-2 18:54:07] Loaded plugin: homebridge-plex
[2018-2-2 18:54:07] Registering accessory 'homebridge-plex.Plex'
[2018-2-2 18:54:07] ---
[2018-2-2 18:54:08] Loaded plugin: homebridge-config-ui-x
[2018-2-2 18:54:08] Registering platform 'homebridge-config-ui-x.config'
[2018-2-2 18:54:08] ---
[2018-2-2 18:54:08] Loaded config.json with 1 accessories and 1 platforms.
[2018-2-2 18:54:08] ---
[2018-2-2 18:54:08] Loading 1 platforms...

/usr/local/lib/node_modules/homebridge/lib/api.js:122
throw new Error("The requested platform '" + name + "' was not registered by any plugin.");

^
Error: The requested platform 'AmazonDash' was not registered by any plugin.

at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
at Function.Module.runMain (module.js:684:10)
at startup (bootstrap_node.js:187:16)
at bootstrap_node.js:608:3
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

[2018-2-2 18:54:14] ====================
[2018-2-2 18:54:14] ERROR LOADING PLUGIN homebridge-amazondash:

[2018-2-2 18:54:14] Error: Cannot find module './build/Release/pcap_binding'

at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/homebridge/node_modules/pcap/pcap.js:3:21)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
[2018-2-2 18:54:14] ====================
[2018-2-2 18:54:14] Loaded plugin: homebridge-plex
[2018-2-2 18:54:14] Registering accessory 'homebridge-plex.Plex'
[2018-2-2 18:54:14] ---
[2018-2-2 18:54:14] Loaded plugin: homebridge-config-ui-x
[2018-2-2 18:54:14] Registering platform 'homebridge-config-ui-x.config'
[2018-2-2 18:54:14] ---
[2018-2-2 18:54:14] Loaded config.json with 1 accessories and 1 platforms.
[2018-2-2 18:54:14] ---
[2018-2-2 18:54:14] Loading 1 platforms...

/usr/local/lib/node_modules/homebridge/lib/api.js:122
throw new Error("The requested platform '" + name + "' was not registered by any plugin.");

^
Error: The requested platform 'AmazonDash' was not registered by any plugin.

at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
at Function.Module.runMain (module.js:684:10)
at startup (bootstrap_node.js:187:16)
at bootstrap_node.js:608:3
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
```

Seems like

**Comment by oznu** [comment]
There might be a conflict using `npm rebuild` with `yarn`.

Can you stop the container and try this setup that worked for me:

1. Delete the `node_modules` folder
2. Remove the `yarn add homebridge-amazondash` line from your `setup.sh`
3. Add `"homebridge-amazondash": "*"` to the `package.json` file
4. Add `npm rebuild` to the `setup.sh` file.

Start the container with `-e "PACKAGES=libpcap-dev"`. 

You can test to make sure this will work without actually updating by removing the container and re-creating it (this is essentially what happens each time you upgrade):

```
docker rm -f <container name or id>
```
