### ISSUE TITLE
Unable to connect to deconz ConBee2

### ISSUE THREAD

**Issue by T3CHN3W** [oznu/docker-homebridge#569]
### Current Situation

Hello, 
I have Homebridge and the Phoscon app running in Docker on my Raspi Pi 4. Unfortunately, I cannot integrate the ConBee2 stick via the PhosconBridge using the HUE app.
If I run Homebridge natively on the Pi, everything works without a problem, but if Homebridge is installed via the Docker, Homebridge cannot find the PhosconBridge.

IP Phoscon-Docker: 192.168.178.208:8085
IP Homebridge-Docker: 192.168.178.208:9090

### Docker Config

```yml
version: '2'
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: bridge
    ports:
    - 9090:8581
    volumes:
      - /volume1/docker/homebridgetest:/homebridge
    environment:
    - PUID=1000
    - PGID=1000
    - HOMEBRIDGE_CONFIG_UI=1
    - HOMEBRIDGE_CONFIG_UI_PORT=9090
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
```

### Logs

```text
[7/7/2024, 11:02:21 AM] Homebridge v1.8.3 (HAP v0.12.2) (Homebridge B1BA) is running on port 51938.
[7/7/2024, 11:05:05 AM] [Homebridge UI] Running Command: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/plugin-upgrade-install.sh homebridge-hue 0.13.70 /var/lib/homebridge/node_modules
[7/7/2024, 11:11:07 AM] [Homebridge UI] Changes to config.json saved.
[7/7/2024, 11:11:10 AM] [Homebridge UI] Homebridge restart request received
[7/7/2024, 11:11:10 AM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[7/7/2024, 11:11:10 AM] [Homebridge UI] Sending SIGTERM to Homebridge
[7/7/2024, 11:11:10 AM] Got SIGTERM, shutting down Homebridge...
[7/7/2024, 11:11:15 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[7/7/2024, 11:11:20 AM] [HB Supervisor] Restarting Homebridge...
[7/7/2024, 11:11:20 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[7/7/2024, 11:11:20 AM] [HB Supervisor] Started Homebridge v1.8.3 with PID: 1101
[7/7/2024, 11:11:21 AM] Loaded config.json with 0 accessories and 2 platforms.
[7/7/2024, 11:11:21 AM] Loaded 0 cached accessories from cachedAccessories.
[7/7/2024, 11:11:21 AM] ---
[7/7/2024, 11:11:24 AM] Loaded plugin: homebridge-hue@0.13.70
[7/7/2024, 11:11:24 AM] Registering platform 'homebridge-hue.Hue'
[7/7/2024, 11:11:24 AM] ---
[7/7/2024, 11:11:24 AM] Loading 2 platforms...
[7/7/2024, 11:11:24 AM] [Hue] Initializing Hue platform...
[7/7/2024, 11:11:24 AM] [Hue] homebridge-hue v0.13.70, node v20.15.0, homebridge v1.8.3
[7/7/2024, 11:11:24 AM] [Hue] warning: recommended version: node v20.10.0 LTS
[7/7/2024, 11:11:24 AM] [Hue] warning: recommended version: homebridge v1.7.0
[7/7/2024, 11:11:24 AM] [Hue] 127.0.0.1: request 1: GET /config
[7/7/2024, 11:11:24 AM] [Hue] 127.0.0.1: request 1: connect ECONNREFUSED 127.0.0.1:8085
[7/7/2024, 11:11:24 AM] [Hue] 127.0.0.1:8085: not found - retrying in 30s
[7/7/2024, 11:11:44 AM] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
...

...
[7/7/2024, 11:16:14 AM] [Homebridge UI] Changes to config.json saved.
[7/7/2024, 11:16:17 AM] [Homebridge UI] Homebridge restart request received
[7/7/2024, 11:16:17 AM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[7/7/2024, 11:16:17 AM] [Homebridge UI] Sending SIGTERM to Homebridge
[7/7/2024, 11:16:17 AM] Got SIGTERM, shutting down Homebridge...
[7/7/2024, 11:16:17 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1004:11)
    at Server.setServerStatus (/homebridge/node_modules/homebridge/src/server.ts:143:45)
    at Server.teardown (/homebridge/node_modules/homebridge/src/server.ts:187:10)
    at signalHandler (/homebridge/node_modules/homebridge/src/cli.ts:94:12)
    at process.emit (node:events:519:28)
    at process.emit (/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[7/7/2024, 11:16:22 AM] [Hue] goodbye
```

### Host Operating System

Raspberry Pi OS - Latest

### Host Architecture

x86_64 / amd64

**Comment by T3CHN3W** [comment]
Just read the line
```
[7/7/2024, 12:36:31 PM] [Hue] Phoscon-GW: warning: support for deCONZ has been deprecated in favour of Homebridge deCONZ
```

--> Installed the Homebridge DeConz app.
In the setting I used the IP + Port of the Deconz docker as mentioned above.

If you get the WARNING:
```
warning: request 1: api error 101:

```
You must authenticate the Homebridge app in Phoscon. To do this, open the Phoscon app and go to "Settings - Gateway", click on "Advanced" and then on "App connection" for third-party apps and restart Homebridge. This should fix the error.

I hope I could help someone who has the same problem.
