### ISSUE TITLE
Error: could not get uid/gid

### ISSUE THREAD

**Issue by julienma** [oznu/docker-homebridge#93]
After starting Homebridge, I have this error.
I don't know what this can affect, as Homebridge seems to work nonetheless.

```js
homebridge_1  | Error: could not get uid/gid
homebridge_1  | [ 'nobody', 0 ]
homebridge_1  |
homebridge_1  |     at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
homebridge_1  |     at ChildProcess.exithandler (child_process.js:282:5)
homebridge_1  |     at emitTwo (events.js:126:13)
homebridge_1  |     at ChildProcess.emit (events.js:214:7)
homebridge_1  |     at maybeClose (internal/child_process.js:925:16)
homebridge_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
homebridge_1  | TypeError: Cannot read property 'get' of undefined
homebridge_1  |     at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
homebridge_1  |     at /usr/lib/node_modules/npm/bin/npm-cli.js:83:20
homebridge_1  |     at cb (/usr/lib/node_modules/npm/lib/npm.js:224:22)
homebridge_1  |     at /usr/lib/node_modules/npm/lib/npm.js:262:24
homebridge_1  |     at /usr/lib/node_modules/npm/lib/config/core.js:81:7
homebridge_1  |     at Array.forEach (<anonymous>)
homebridge_1  |     at /usr/lib/node_modules/npm/lib/config/core.js:80:13
homebridge_1  |     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
homebridge_1  |     at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:178:20)
homebridge_1  |     at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:236:22)
homebridge_1  |     at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:39:14
homebridge_1  |     at ChildProcess.exithandler (child_process.js:282:5)
homebridge_1  |     at emitTwo (events.js:126:13)
homebridge_1  |     at ChildProcess.emit (events.js:214:7)
homebridge_1  |     at maybeClose (internal/child_process.js:925:16)
homebridge_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
homebridge_1  | /usr/lib/node_modules/npm/lib/utils/error-handler.js:205
homebridge_1  |   if (npm.config.get('json')) {
homebridge_1  |                  ^
homebridge_1  |
homebridge_1  | TypeError: Cannot read property 'get' of undefined
homebridge_1  |     at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
homebridge_1  |     at emitOne (events.js:116:13)
homebridge_1  |     at process.emit (events.js:211:7)
homebridge_1  |     at process._fatalException (bootstrap_node.js:375:26)
```

FYI, I'm using an [`aarch64` image](https://github.com/oznu/docker-homebridge/issues/91).

I think the UID/GUID are what they should be:

```sh
pi@nanopineo2 ~/homebridge> id
uid=1000(pi) gid=1000(pi) groups=1000(pi),20(dialout),27(sudo),29(audio),44(video),46(plugdev),101(systemd-journal),109(netdev),112(ssh),999(docker)
```

This is my `docker-compose.yml`:

```yaml
version: '2'
services:
  homebridge:
    image: oznu/homebridge:aarch64
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    environment:
      - TZ=Europe/Paris
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
```

Full log:

```sh
pi@nanopineo2 ~/homebridge> docker-compose up -d
Creating homebridge_homebridge_1 ... done
pi@nanopineo2 ~/homebridge> docker-compose logs -f
Attaching to homebridge_homebridge_1
homebridge_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
homebridge_1  | [s6-init] ensuring user provided files have correct perms...exited 0.
homebridge_1  | [fix-attrs.d] applying ownership & permissions fixes...
homebridge_1  | [fix-attrs.d] done.
homebridge_1  | [cont-init.d] executing container initialization scripts...
homebridge_1  | [cont-init.d] 10-adduser: executing...
homebridge_1  |
homebridge_1  | -------------------------------------
homebridge_1  | GID/UID
homebridge_1  | -------------------------------------
homebridge_1  | User uid:    1000
homebridge_1  | User gid:    1000
homebridge_1  | -------------------------------------
homebridge_1  |
homebridge_1  | [cont-init.d] 10-adduser: exited 0.
homebridge_1  | [cont-init.d] 20-set-timezone: executing...
homebridge_1  | [cont-init.d] 20-set-timezone: exited 0.
homebridge_1  | [cont-init.d] 30-packages: executing...
homebridge_1  | [cont-init.d] 30-packages: exited 0.
homebridge_1  | [cont-init.d] 40-dbus-avahi: executing...
homebridge_1  | [cont-init.d] 40-dbus-avahi: exited 0.
homebridge_1  | [cont-init.d] 45-user-data: executing...
homebridge_1  | [cont-init.d] 45-user-data: exited 0.
homebridge_1  | [cont-init.d] 50-plugins: executing...
homebridge_1  | Homebridge: Installing plugins...
homebridge_1  | npm WARN homebridge No description
homebridge_1  | npm WARN homebridge No repository field.
homebridge_1  | npm WARN homebridge No license field.
homebridge_1  |
homebridge_1  | up to date in 6.682s
homebridge_1  | npm WARN homebridge No description
homebridge_1  | npm WARN homebridge No repository field.
homebridge_1  | npm WARN homebridge No license field.
homebridge_1  |
homebridge_1  | up to date in 6.805s
homebridge_1  | [cont-init.d] 50-plugins: exited 0.
homebridge_1  | [cont-init.d] 55-config-ui: executing...
homebridge_1  | Enabling homebridge-config-ui-x...
homebridge_1  | [cont-init.d] 55-config-ui: exited 1.
homebridge_1  | [cont-init.d] done.
homebridge_1  | [services.d] starting services
homebridge_1  | Starting dbus-daemon
homebridge_1  | [services.d] done.
homebridge_1  | Starting Avahi daemon
homebridge_1  | Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
homebridge_1  | Successfully dropped root privileges.
homebridge_1  | avahi-daemon 0.6.32 starting up.
homebridge_1  | WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
homebridge_1  | Loading service file /etc/avahi/services/sftp-ssh.service.
homebridge_1  | Loading service file /etc/avahi/services/ssh.service.
homebridge_1  | Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
homebridge_1  | New relevant interface docker0.IPv4 for mDNS.
homebridge_1  | Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.1.50.
homebridge_1  | New relevant interface eth0.IPv4 for mDNS.
homebridge_1  | Network interface enumeration completed.
homebridge_1  | Registering new address record for 172.17.0.1 on docker0.IPv4.
homebridge_1  | Registering new address record for fe80::1:3fff:feed:a6bd on eth0.*.
homebridge_1  | Registering new address record for 192.168.1.50 on eth0.IPv4.
homebridge_1  | Registering new address record for 192.168.1.164 on eth0.IPv4.
homebridge_1  | Server startup complete. Host name is nanopineo2.local. Local service cookie is 2627706528.
homebridge_1  | Service "nanopineo2" (/etc/avahi/services/ssh.service) successfully established.
homebridge_1  | Service "nanopineo2" (/etc/avahi/services/sftp-ssh.service) successfully established.
homebridge_1  | -U /homebridge -P /homebridge/node_modules
homebridge_1  | *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
homebridge_1  | *** WARNING *** Please fix your application to use the native API of Avahi!
homebridge_1  | *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
homebridge_1  | *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
homebridge_1  | *** WARNING *** Please fix your application to use the native API of Avahi!
homebridge_1  | *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
homebridge_1  | Error: could not get uid/gid
homebridge_1  | [ 'nobody', 0 ]
homebridge_1  |
homebridge_1  |     at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
homebridge_1  |     at ChildProcess.exithandler (child_process.js:282:5)
homebridge_1  |     at emitTwo (events.js:126:13)
homebridge_1  |     at ChildProcess.emit (events.js:214:7)
homebridge_1  |     at maybeClose (internal/child_process.js:925:16)
homebridge_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
homebridge_1  | TypeError: Cannot read property 'get' of undefined
homebridge_1  |     at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
homebridge_1  |     at /usr/lib/node_modules/npm/bin/npm-cli.js:83:20
homebridge_1  |     at cb (/usr/lib/node_modules/npm/lib/npm.js:224:22)
homebridge_1  |     at /usr/lib/node_modules/npm/lib/npm.js:262:24
homebridge_1  |     at /usr/lib/node_modules/npm/lib/config/core.js:81:7
homebridge_1  |     at Array.forEach (<anonymous>)
homebridge_1  |     at /usr/lib/node_modules/npm/lib/config/core.js:80:13
homebridge_1  |     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
homebridge_1  |     at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:178:20)
homebridge_1  |     at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:236:22)
homebridge_1  |     at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:39:14
homebridge_1  |     at ChildProcess.exithandler (child_process.js:282:5)
homebridge_1  |     at emitTwo (events.js:126:13)
homebridge_1  |     at ChildProcess.emit (events.js:214:7)
homebridge_1  |     at maybeClose (internal/child_process.js:925:16)
homebridge_1  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
homebridge_1  | /usr/lib/node_modules/npm/lib/utils/error-handler.js:205
homebridge_1  |   if (npm.config.get('json')) {
homebridge_1  |                  ^
homebridge_1  |
homebridge_1  | TypeError: Cannot read property 'get' of undefined
homebridge_1  |     at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
homebridge_1  |     at emitOne (events.js:116:13)
homebridge_1  |     at process.emit (events.js:211:7)
homebridge_1  |     at process._fatalException (bootstrap_node.js:375:26)
homebridge_1  | [2018-4-3 19:14:24] [homebridge-config-ui-x] Using Form Authentication
homebridge_1  | [2018-4-3 19:14:24] [homebridge-config-ui-x] Console is listening on port 8080.
homebridge_1  | [2018-4-3 19:14:25] [homebridge-config-ui-x] Invalid token sent by admin: invalid signature
homebridge_1  | [2018-4-3 19:14:27] Plugin /homebridge/node_modules/homebridge-dacp requires Node version of >=9.3.0 which does not satisfy the current Node version of v8.11.1. You may need to upgrade your installation of Node.
homebridge_1  | *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
homebridge_1  | *** WARNING *** Please fix your application to use the native API of Avahi!
homebridge_1  | *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
homebridge_1  | [2018-4-3 19:14:29] Loaded plugin: homebridge-dacp
homebridge_1  | [2018-4-3 19:14:29] Registering platform 'homebridge-dacp.DACP'
homebridge_1  | [2018-4-3 19:14:29] ---
homebridge_1  | [2018-4-3 19:14:31] Loaded plugin: homebridge-hue
homebridge_1  | [2018-4-3 19:14:31] Registering platform 'homebridge-hue.Hue'
homebridge_1  | [2018-4-3 19:14:31] ---
homebridge_1  | [2018-4-3 19:14:32] Loaded plugin: homebridge-config-ui-x
homebridge_1  | [2018-4-3 19:14:32] Registering platform 'homebridge-config-ui-x.config'
homebridge_1  | [2018-4-3 19:14:32] ---
homebridge_1  | [2018-4-3 19:14:32] Loaded config.json with 0 accessories and 2 platforms.
homebridge_1  | [2018-4-3 19:14:32] ---
homebridge_1  | [2018-4-3 19:14:32] Loading 2 platforms...
homebridge_1  | [2018-4-3 19:14:32] [Hue] Initializing Hue platform...
homebridge_1  | [2018-4-3 19:14:32] [Hue] homebridge-hue v0.8.9, node v8.11.1, homebridge v0.4.38
homebridge_1  | [2018-4-3 19:14:32] [DACP] Initializing DACP platform...
homebridge_1  | [2018-4-3 19:14:32] [DACP] DACP Platform Plugin Loaded - Version 0.9.1
homebridge_1  | [2018-4-3 19:14:32] [DACP] Found accessory in config: "AppleTV"
homebridge_1  | [2018-4-3 19:14:32] [DACP] Initializing platform accessory 'AppleTV'...
homebridge_1  | [2018-4-3 19:14:32] Loading 0 accessories...
homebridge_1  | [2018-4-3 19:14:32] [DACP] Starting DACP browser...
homebridge_1  | [2018-4-3 19:14:34] [Hue] dresden appspot ipv6: communication error ENETUNREACH on https://dresden-light.appspot.com/
homebridge_1  | [2018-4-3 19:14:34] [DACP] The accessory AppleTV is announced as 192.168.1.133:3689.
homebridge_1  | [2018-4-3 19:14:34] [DACP] It's an AppleTV5,3 named Apple TV D&J
homebridge_1  | [2018-4-3 19:14:34] [DACP] Attempting to reconnect to AppleTV in 0.1 seconds.
homebridge_1  | [2018-4-3 19:14:34] [DACP] Connecting to AppleTV (192.168.1.133:3689)
homebridge_1  | [2018-4-3 19:14:34] [DACP] Creating status connection to 192.168.1.133:3689
homebridge_1  | Established connection to 192.168.1.133:3689 with session ID 12
homebridge_1  | [2018-4-3 19:14:35] [DACP] Connected to Apple TV D&J
homebridge_1  | [2018-4-3 19:14:39] [Hue] Philips hue: Philips BSB002 bridge v1802201122, api v1.24.0
homebridge_1  | [2018-4-3 19:14:39] [Hue] Philips hue: 4 accessories
homebridge_1  | [2018-4-3 19:14:39] [Hue] masked debug info dumped to /homebridge/homebridge-hue.json.gz
homebridge_1  | [2018-4-3 19:14:39] [Hue] Initializing platform accessory 'Philips hue'...
homebridge_1  | [2018-4-3 19:14:39] [Hue] Philips hue: 3 services
homebridge_1  | [2018-4-3 19:14:39] [Hue] Initializing platform accessory 'Ikea E27 - 1'...
homebridge_1  | [2018-4-3 19:14:39] [Hue] Initializing platform accessory 'Ikea E14 - 2'...
homebridge_1  | [2018-4-3 19:14:39] [Hue] Initializing platform accessory 'Ikea E14 - 3'...
homebridge_1  | Setup Payload:
homebridge_1  | X-HM://0023ISYWYFHNJ
homebridge_1  | Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  |
homebridge_1  | Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
homebridge_1  |
homebridge_1  |     ┌────────────┐
homebridge_1  |     │ 031-45-154 │
homebridge_1  |     └────────────┘
homebridge_1  |
homebridge_1  | [2018-4-3 19:14:41] Homebridge is running on port 51826.
```

**Comment by julienma** [comment]
Thanks!

**Comment by javierojeda94** [comment]
Why does this error happen and why is that `npm config set unsafe-perm true` command the solution? 

I had this problem for about two days :( at least I wanna know what my enemy was

**Comment by oznu** [comment]
I'm not sure exactly why this only occurred on the aarch64 variant of the image.

Last nights build, that upgraded node to 8.11.2, has the flag set by default for all variants.

**Comment by javierojeda94** [comment]
It is really weird... I'm running my pipelines on bitbucket and they work perfectly everytime. That problem just appeared out of nowhere

**Comment by oznu** [comment]
Check this:

```
https://github.com/npm/uid-number/issues/3
```

**Comment by sixth** [comment]
@javierojeda94 same here. please mention your issue here - https://bitbucket.org/site/master/issues/16334/pipelines-failing-with-could-not-get-uid
